import EcoLean.GameTheory.MathLanguage.MathematicalStructures
import Mathlib.Logic.Function.Basic
import Mathlib.Data.Real.Basic

namespace EcoLean.GameTheory

universe u v w

/--
A profile with index set `I` and codomain `X`.
This matches Battigalli's use of a profile as a function on an index set.
-/
abbrev Profile (I : Type u) (X : Sort v) := I → X

/--
A dependent profile for an indexed family `A`.
Later action profiles will usually have this form.
-/
abbrev DProfile {I : Type u} (A : I → Sort v) := ∀ i, A i

namespace DProfile

section Update

variable {I : Type u} {A : I → Sort v} [DecidableEq I]

/--
Update the `i`-th component of a dependent profile.
-/
abbrev update (a : DProfile A) (i : I) (ai : A i) : DProfile A :=
  Function.update a i ai

@[simp] theorem update_self (a : DProfile A) (i : I) (ai : A i) :
    update a i ai i = ai := by
  simp [update, Function.update]

theorem update_ne (a : DProfile A) {i j : I} (ai : A i) (h : j ≠ i) :
    update a i ai j = a j := by
  simp [update, Function.update, h]

@[simp] theorem update_eq_self (a : DProfile A) (i : I) :
    update a i (a i) = a := by
  funext j
  by_cases h : j = i
  · subst h
    simp [update, Function.update]
  · simp [update, Function.update, h]

end Update

end DProfile

/--
An abstract game form:
players, their feasible actions, a set of outcomes,
and a rule assigning an outcome to each action profile.

This captures the rules of interaction without yet encoding utilities.
-/
structure GameForm where
  Player  : Type u
  Action  : Player → Type v
  Outcome : Type w
  outcome : DProfile Action → Outcome

namespace GameForm

/-- The type of action profiles of a game form. -/
abbrev ActionProfile (G : GameForm) := DProfile G.Action

/-- The outcome generated by an action profile. -/
def eval (G : GameForm) (a : G.ActionProfile) : G.Outcome :=
  G.outcome a

/-- Unilateral deviation from an action profile. -/
def deviate (G : GameForm) [DecidableEq G.Player]
    (a : G.ActionProfile) (i : G.Player) (ai : G.Action i) : G.ActionProfile :=
  DProfile.update a i ai

@[simp] theorem deviate_self (G : GameForm) [DecidableEq G.Player]
    (a : G.ActionProfile) (i : G.Player) (ai : G.Action i) :
    G.deviate a i ai i = ai := by
  simp [GameForm.deviate]

theorem deviate_ne (G : GameForm) [DecidableEq G.Player]
    (a : G.ActionProfile) {i j : G.Player} (ai : G.Action i) (h : j ≠ i) :
    G.deviate a i ai j = a j := by
  simp [GameForm.deviate, DProfile.update_ne, h]

@[simp] theorem deviate_eq_self (G : GameForm) [DecidableEq G.Player]
    (a : G.ActionProfile) (i : G.Player) :
    G.deviate a i (a i) = a := by
  simp [GameForm.deviate]

end GameForm

/--
A game is a game form together with players' utility functions over outcomes.
-/
structure Game extends GameForm where
  utility : Player → Outcome → ℝ

namespace Game

/-- The type of action profiles of a game. -/
abbrev ActionProfile (Γ : Game) := Γ.toGameForm.ActionProfile

/-- The outcome induced by an action profile. -/
def outcomeOf (Γ : Game) (a : Γ.ActionProfile) : Γ.Outcome :=
  Γ.outcome a

/-- Player `i`'s utility from an action profile. -/
def payoff (Γ : Game) (i : Γ.Player) (a : Γ.ActionProfile) : ℝ :=
  Γ.utility i (Γ.outcome a)

/-- The utility profile induced by an action profile. -/
def payoffProfile (Γ : Game) (a : Γ.ActionProfile) : Profile Γ.Player ℝ :=
  fun i => Γ.payoff i a

@[simp] theorem payoffProfile_apply (Γ : Game) (a : Γ.ActionProfile) (i : Γ.Player) :
    Γ.payoffProfile a i = Γ.payoff i a := rfl

end Game

end EcoLean.GameTheory
