import EcoLean.GameTheory.MathLanguage.MathematicalStructures

namespace EcoLean.GameTheory

universe u v w

/--
A profile with index set `I` and common codomain `X`.
This matches Battigalli's use of “profile” as a function on an index set.
-/
abbrev Profile (I : Type u) (X : Type v) := I → X

/--
A profile for a player-dependent family of sets.
Later action profiles will usually have this form.
-/
abbrev DProfile {I : Type u} (A : I → Type v) := ∀ i, A i

namespace DProfile

section Update

variable {I : Type u} {A : I → Type v}

/--
Update the `i`-th component of a dependent profile.
-/
def update (a : DProfile A) (i : I) (ai : A i) : DProfile A :=
  fun j =>
    if h : j = i then
      Eq.ndrec ai h.symm
    else
      a j

@[simp] theorem update_self (a : DProfile A) (i : I) (ai : A i) :
    update a i ai i = ai := by
  simp [update]

theorem update_ne (a : DProfile A) {i j : I} (ai : A i) (h : j ≠ i) :
    update a i ai j = a j := by
  simp [update, h]

@[simp] theorem update_eq_self (a : DProfile A) (i : I) :
    update a i (a i) = a := by
  funext j
  by_cases h : j = i
  · subst h
    simp [update]
  · simp [update, h]

end Update

end DProfile

/--
An abstract game form:
players, their feasible actions, a set of outcomes,
and a rule assigning an outcome to each action profile.

This captures the rules of interaction without yet encoding utilities.
-/
structure GameForm where
  Player  : Type u
  Action  : Player → Type v
  Outcome : Type w
  outcome : DProfile Action → Outcome

namespace GameForm

/-- The set of action profiles of a game form. -/
abbrev ActionProfile (G : GameForm) : Type (max u v) := DProfile G.Action

/-- The outcome generated by an action profile. -/
def eval (G : GameForm) (a : ActionProfile G) : G.Outcome :=
  G.outcome a

/-- Unilateral deviation from an action profile. -/
def deviate (G : GameForm) (a : ActionProfile G)
    (i : G.Player) (ai : G.Action i) : ActionProfile G :=
  DProfile.update a i ai

@[simp] theorem deviate_self (G : GameForm) (a : ActionProfile G)
    (i : G.Player) (ai : G.Action i) :
    deviate G a i ai i = ai := by
  simp [deviate]

theorem deviate_ne (G : GameForm) (a : ActionProfile G)
    {i j : G.Player} (ai : G.Action i) (h : j ≠ i) :
    deviate G a i ai j = a j := by
  simp [deviate, DProfile.update_ne, h]

@[simp] theorem deviate_eq_self (G : GameForm) (a : ActionProfile G)
    (i : G.Player) :
    deviate G a i (a i) = a := by
  simp [deviate]

end GameForm

/--
A game is a game form together with players' utility functions over outcomes.
-/
structure Game extends GameForm where
  utility : Player → Outcome → ℝ

namespace Game

/-- The action-profile type of a game. -/
abbrev ActionProfile (Γ : Game) : Type (max u v) := GameForm.ActionProfile Γ.toGameForm

/-- The outcome induced by an action profile. -/
def outcomeOf (Γ : Game) (a : ActionProfile Γ) : Γ.Outcome :=
  Γ.outcome a

/-- Player `i`'s utility from an action profile. -/
def payoff (Γ : Game) (i : Γ.Player) (a : ActionProfile Γ) : ℝ :=
  Γ.utility i (Γ.outcome a)

/-- The utility profile induced by an action profile. -/
def payoffProfile (Γ : Game) (a : ActionProfile Γ) : Profile Γ.Player ℝ :=
  fun i => payoff Γ i a

@[simp] theorem payoffProfile_apply (Γ : Game) (a : ActionProfile Γ) (i : Γ.Player) :
    payoffProfile Γ a i = payoff Γ i a := rfl

end Game

end EcoLean.GameTheory
