import EcoLean.ChoicePreferenceUtility.Choice
import Mathlib.Data.Set.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Order.Preorder.Finite
import Mathlib.Order.Minimal

universe u

namespace EcoLean

/--
A preference relation on a domain `α`.

The primitive notion is weak preference.
-/
structure Preference (α : Type u) where
  weakPref : α → α → Prop

namespace Preference

variable {α : Type u} (P : Preference α)

/-! ### Derived relations and rationality properties -/

/-- Strict preference derived from weak preference. -/
def StrictPref (x y : α) : Prop :=
  P.weakPref x y ∧ ¬ P.weakPref y x

/-- Indifference derived from weak preference. -/
def Indiff (x y : α) : Prop :=
  P.weakPref x y ∧ P.weakPref y x

/-- Incomparability derived from weak preference. -/
def Incomparable (x y : α) : Prop :=
  ¬ P.weakPref x y ∧ ¬ P.weakPref y x

/-- Reflexivity of weak preference. -/
def Reflexive : Prop :=
  ∀ x : α, P.weakPref x x

/-- Completeness of weak preference. -/
def Complete : Prop :=
  ∀ x y : α, P.weakPref x y ∨ P.weakPref y x

/-- Transitivity of weak preference. -/
def Transitive : Prop :=
  ∀ x y z : α, P.weakPref x y → P.weakPref y z → P.weakPref x z

/-- A total preorder preference. -/
def TotalPreorder : Prop :=
  P.Reflexive ∧ P.Transitive ∧ P.Complete

scoped notation:50 x " ≽[" P "] " y => Preference.weakPref P x y
scoped notation:50 x " ≻[" P "] " y => Preference.StrictPref P x y
scoped notation:50 x " ∼[" P "] " y => Preference.Indiff P x y

/-- Unfolding lemma for strict preference. -/
theorem strictPref_def (x y : α) :
    P.StrictPref x y ↔ P.weakPref x y ∧ ¬ P.weakPref y x := by
  rfl

/-- Unfolding lemma for indifference. -/
theorem indiff_def (x y : α) :
    P.Indiff x y ↔ P.weakPref x y ∧ P.weakPref y x := by
  rfl

/-- Unfolding lemma for incomparability. -/
theorem incomparable_def (x y : α) :
    P.Incomparable x y ↔ ¬ P.weakPref x y ∧ ¬ P.weakPref y x := by
  rfl

/-- Completeness implies reflexivity. -/
theorem weakPref_refl_of_complete
    (hC : P.Complete) (x : α) :
    P.weakPref x x := by
  cases hC x x with
  | inl hxx => exact hxx
  | inr hxx => exact hxx

/--
The choice function generated by preference maximization.

This is Kreps' formula `c_≽(A) = {x ∈ A : x ≽ y for all y ∈ A}`.
-/
def generatedChoice : ChoiceFunction α where
  choose A := {x : α | x ∈ A ∧ ∀ y : α, y ∈ A → P.weakPref x y}

/-- The choice function generated by a preference chooses only from the feasible set. -/
theorem generatedChoice_choosesFrom :
    (P.generatedChoice).ChoosesFrom := by
  intro A x hx
  exact hx.1

/--
If `x` is chosen by preference maximization from `A`,
then `x` is weakly preferred to every feasible alternative in `A`.
-/
theorem weakPref_of_mem_generatedChoice
    {A : Set α} {x y : α}
    (hx : x ∈ (P.generatedChoice).choose A)
    (hy : y ∈ A) :
    P.weakPref x y := by
  exact hx.2 y hy

/-- Strict preference implies weak preference. -/
theorem weakPref_of_strictPref {x y : α} :
    P.StrictPref x y → P.weakPref x y := by
  intro hxy
  exact hxy.1

/-- Strict preference rules out the reverse weak preference. -/
theorem not_weakPref_of_strictPref {x y : α} :
    P.StrictPref x y → ¬ P.weakPref y x := by
  intro hxy
  exact hxy.2

/-- Indifference implies weak preference in the first direction. -/
theorem weakPref_left_of_indiff {x y : α} :
    P.Indiff x y → P.weakPref x y := by
  intro hxy
  exact hxy.1

/-- Indifference implies weak preference in the second direction. -/
theorem weakPref_right_of_indiff {x y : α} :
    P.Indiff x y → P.weakPref y x := by
  intro hxy
  exact hxy.2

/-- Indifference is symmetric. -/
theorem indiff_symm {x y : α} :
    P.Indiff x y → P.Indiff y x := by
  intro hxy
  exact ⟨hxy.2, hxy.1⟩

/-- Incomparability is symmetric. -/
theorem incomparable_symm {x y : α} :
    P.Incomparable x y → P.Incomparable y x := by
  intro hxy
  exact ⟨hxy.2, hxy.1⟩

/-- Strict preference excludes indifference. -/
theorem strictPref_not_indiff {x y : α} :
    P.StrictPref x y → ¬ P.Indiff x y := by
  intro hxy hInd
  exact hxy.2 hInd.2

/-- Strict preference is asymmetric. -/
theorem strictPref_asymm {x y : α} :
    P.StrictPref x y → ¬ P.StrictPref y x := by
  intro hxy hyx
  exact hxy.2 hyx.1

/-- Reflexivity implies self-indifference. -/
theorem indiff_refl_of_reflexive
    (hR : P.Reflexive) (x : α) :
    P.Indiff x x := by
  exact ⟨hR x, hR x⟩

/-- Under reflexivity, strict preference is irreflexive. -/
theorem not_strictPref_self_of_reflexive
    (hR : P.Reflexive) (x : α) :
    ¬ P.StrictPref x x := by
  intro hxx
  exact hxx.2 (hR x)

/--
If a preference relation is complete and transitive, then every finite nonempty
feasible set contains an element weakly preferred to every other feasible element.
-/
theorem exists_best_of_finite_of_complete_transitive
    (hC : P.Complete)
    (hT : P.Transitive)
    {A : Set α}
    (hFin : A.Finite)
    (hNE : A.Nonempty) :
    ∃ x : α, x ∈ A ∧ ∀ y : α, y ∈ A → P.weakPref x y := by
  classical
  letI : LE α := ⟨fun a b => P.weakPref b a⟩
  letI : IsTrans α (fun a b => P.weakPref b a) := ⟨by
    intro a b c hab hbc
    exact hT c b a hbc hab
  ⟩

  rcases Set.Finite.exists_maximal (s := A) hFin hNE with ⟨x, hxMax⟩
  have hxA : x ∈ A := hxMax.1

  refine ⟨x, hxA, ?_⟩
  intro y hyA
  by_cases hxy : P.weakPref x y
  · exact hxy
  · have hyx : P.weakPref y x := by
      cases hC x y with
      | inl h =>
          exact False.elim (hxy h)
      | inr h =>
          exact h
    have hNotMax : ¬ Maximal (fun z : α => z ∈ A) x := by
      exact (not_maximal_iff hxA).2 ⟨y, hyA, hyx, hxy⟩
    exact False.elim (hNotMax hxMax)

/-- Under transitivity, strict preference is transitive. -/
theorem strictPref_trans_of_transitive
    (hT : P.Transitive) {x y z : α} :
    P.StrictPref x y → P.StrictPref y z → P.StrictPref x z := by
  intro hxy hyz
  refine ⟨hT x y z hxy.1 hyz.1, ?_⟩
  intro hzx
  have hzy : P.weakPref z y := hT z x y hzx hxy.1
  exact hyz.2 hzy

/-- Under transitivity, indifference is transitive. -/
theorem indiff_trans_of_transitive
    (hT : P.Transitive) {x y z : α} :
    P.Indiff x y → P.Indiff y z → P.Indiff x z := by
  intro hxy hyz
  constructor
  · exact hT x y z hxy.1 hyz.1
  · exact hT z y x hyz.2 hxy.2

/-- Completeness rules out incomparability. -/
theorem not_incomparable_of_complete
    (hC : P.Complete) (x y : α) :
    ¬ P.Incomparable x y := by
  intro hInc
  cases hC x y with
  | inl hxy =>
      exact hInc.1 hxy
  | inr hyx =>
      exact hInc.2 hyx

/--
If `x ≽ y`, then either `x ≻ y` or `x ∼ y`.
-/
theorem strict_or_indiff_of_weakPref
    {x y : α} (hxy : P.weakPref x y) :
    P.StrictPref x y ∨ P.Indiff x y := by
  by_cases hyx : P.weakPref y x
  · right
    exact ⟨hxy, hyx⟩
  · left
    exact ⟨hxy, hyx⟩

/--
Under completeness, for any two objects either `x ≻ y`, or `y ≻ x`, or `x ∼ y`.
-/
theorem complete_cases
    (hC : P.Complete) (x y : α) :
    P.StrictPref x y ∨ P.StrictPref y x ∨ P.Indiff x y := by
  cases hC x y with
  | inl hxy =>
      by_cases hyx : P.weakPref y x
      · exact Or.inr (Or.inr ⟨hxy, hyx⟩)
      · exact Or.inl ⟨hxy, hyx⟩
  | inr hyx =>
      by_cases hxy : P.weakPref x y
      · exact Or.inr (Or.inr ⟨hxy, hyx⟩)
      · exact Or.inr (Or.inl ⟨hyx, hxy⟩)

/-- Packaging lemma for total preorders. -/
theorem totalPreorder_intro
    (hR : P.Reflexive)
    (hT : P.Transitive)
    (hC : P.Complete) :
    P.TotalPreorder := by
  exact ⟨hR, hT, hC⟩

/--
If a preference relation is complete and transitive, then the generated
choice function satisfies choice coherence.
-/
theorem generatedChoice_choiceCoherent
    (hC : P.Complete)
    (hT : P.Transitive) :
    (P.generatedChoice).ChoiceCoherent := by
  let _ := hC
  intro A B x y hxA hyA hxB hyB hxChooseA hyNotChooseA
  have hxy : P.weakPref x y := hxChooseA.2 y hyA

  have hWitness : ∃ z : α, z ∈ A ∧ ¬ P.weakPref y z := by
    by_contra hNo
    apply hyNotChooseA
    constructor
    · exact hyA
    · intro z hz
      by_contra hyz
      exact hNo ⟨z, hz, hyz⟩

  rcases hWitness with ⟨z, hzA, hyNotz⟩

  have hyNotx : ¬ P.weakPref y x := by
    intro hyx
    have hyz : P.weakPref y z := hT y x z hyx (hxChooseA.2 z hzA)
    exact hyNotz hyz

  intro hyChooseB
  have hyxB : P.weakPref y x := hyChooseB.2 x hxB
  exact hyNotx hyxB

/--
If a preference relation is complete and transitive, then the generated
choice function satisfies finite nonemptiness.
-/
theorem generatedChoice_finiteNonempty
    (hC : P.Complete)
    (hT : P.Transitive) :
    (P.generatedChoice).FiniteNonempty := by
  intro A hFin hNE
  rcases exists_best_of_finite_of_complete_transitive P hC hT hFin hNE with
    ⟨x, hxA, hxBest⟩
  refine ⟨x, ?_⟩
  constructor
  · exact hxA
  · exact hxBest

end Preference

namespace ChoiceFunction

variable {α : Type u} (c : ChoiceFunction α)

/-! ### Preference generated by pairwise choice -/

/--
The preference relation generated by pairwise choice.

Following Kreps, `x ≽_c y` holds if `x ∈ c({x, y})`.
-/
def generatedPref : Preference α where
  weakPref x y := x ∈ c.choose ({x, y} : Set α)

/--
The choice function generated from the preference induced by `c`.

This is `c_{≽c}` in Kreps.
-/
def generatedChoiceFromGeneratedPref : ChoiceFunction α :=
  (generatedPref c).generatedChoice

/--
An equivalent contrapositive form of choice coherence.

If `x` is chosen from `A` and `y` is chosen from `B`, with `x` and `y` feasible in
both, then `y` is chosen from `A` and `x` is chosen from `B`.
-/
theorem choiceCoherent_contrapos
    (hCC : c.ChoiceCoherent)
    {A B : Set α} {x y : α}
    (hxA : x ∈ A) (hyA : y ∈ A)
    (hxB : x ∈ B) (hyB : y ∈ B)
    (hxChooseA : x ∈ c.choose A)
    (hyChooseB : y ∈ c.choose B) :
    y ∈ c.choose A ∧ x ∈ c.choose B := by
  constructor
  · by_contra hyNotA
    exact (hCC hxA hyA hxB hyB hxChooseA hyNotA) hyChooseB
  · by_contra hxNotB
    exact (hCC hyB hxB hyA hxA hyChooseB hxNotB) hxChooseA

/--
If `c` satisfies finite nonemptiness and chooses only from feasible sets,
then the preference `≽_c` is complete.
-/
theorem generatedPref_complete
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty) :
    (generatedPref c).Complete := by
  intro x y
  have hNE : (c.choose ({x, y} : Set α)).Nonempty :=
    pair_choice_nonempty c hFN x y
  rcases hNE with ⟨z, hz⟩
  rcases mem_pair_of_mem_choose_pair c hFrom hz with hzx | hzy
  · subst hzx
    exact Or.inl (by simpa [generatedPref] using hz)
  · subst hzy
    exact Or.inr (by simpa [generatedPref, Set.pair_comm] using hz)

/--
If `c` satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent, then the preference `≽_c` is transitive.
-/
theorem generatedPref_transitive
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedPref c).Transitive := by
  intro x y z hxy hyz

  let T : Set α := ({x, y, z} : Set α)

  have hTNE : (c.choose T).Nonempty := by
    apply hFN
    ·
      change ({x, y, z} : Set α).Finite
      exact Set.Finite.insert x (Set.Finite.insert y (Set.finite_singleton z))
    ·
      exact ⟨x, by simp [T]⟩

  have hxT : x ∈ c.choose T := by
    by_contra hxNotT

    have hyNotT : y ∉ c.choose T := by
      intro hyT
      have hxNotXY : x ∉ c.choose ({x, y} : Set α) :=
        hCC
          (by simp [T])
          (by simp [T])
          (by simp)
          (by simp)
          hyT
          hxNotT
      exact hxNotXY hxy

    have hzNotT : z ∉ c.choose T := by
      intro hzT
      have hyNotYZ : y ∉ c.choose ({y, z} : Set α) :=
        hCC
          (by simp [T])
          (by simp [T])
          (by simp)
          (by simp)
          hzT
          hyNotT
      exact hyNotYZ hyz

    rcases hTNE with ⟨w, hw⟩
    have hwT : w ∈ T := hFrom T hw
    have hwCases : w = x ∨ w = y ∨ w = z := by
      simpa [T] using hwT
    cases hwCases with
    | inl hwx =>
        subst hwx
        exact hxNotT hw
    | inr hrest =>
        cases hrest with
        | inl hwy =>
            subst hwy
            exact hyNotT hw
        | inr hwz =>
            subst hwz
            exact hzNotT hw

  have hxXZ : x ∈ c.choose ({x, z} : Set α) := by
    by_contra hxNotXZ
    have hzXZ : z ∈ c.choose ({x, z} : Set α) :=
      other_mem_choose_of_not_mem_choose_pair c hFrom hFN hxNotXZ
    have hxNotT' : x ∉ c.choose T :=
      hCC
        (by simp)
        (by simp)
        (by simp [T])
        (by simp [T])
        hzXZ
        hxNotXZ
    exact hxNotT' hxT

  exact hxXZ

/-- The preference-generated choice function `c_{≽c}` chooses only from the feasible set. -/
theorem generatedChoiceFromGeneratedPref_choosesFrom :
    (generatedChoiceFromGeneratedPref c).ChoosesFrom := by
  exact Preference.generatedChoice_choosesFrom (P := generatedPref c)

/--
The preference-generated choice function `c_{≽c}` satisfies choice coherence,
provided `c` itself satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent.
-/
theorem generatedChoiceFromGeneratedPref_choiceCoherent
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedChoiceFromGeneratedPref c).ChoiceCoherent := by
  have hComp : (generatedPref c).Complete :=
    generatedPref_complete c hFrom hFN
  have hTrans : (generatedPref c).Transitive :=
    generatedPref_transitive c hFrom hFN hCC
  simpa [generatedChoiceFromGeneratedPref] using
    (Preference.generatedChoice_choiceCoherent
      (P := generatedPref c) hComp hTrans)

/--
The preference-generated choice function `c_{≽c}` satisfies finite nonemptiness,
provided `c` itself satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent.
-/
theorem generatedChoiceFromGeneratedPref_finiteNonempty
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedChoiceFromGeneratedPref c).FiniteNonempty := by
  have hComp : (generatedPref c).Complete :=
    generatedPref_complete c hFrom hFN
  have hTrans : (generatedPref c).Transitive :=
    generatedPref_transitive c hFrom hFN hCC
  simpa [generatedChoiceFromGeneratedPref] using
    (Preference.generatedChoice_finiteNonempty
      (P := generatedPref c) hComp hTrans)

/--
Every element chosen by `c` is also chosen by `c_{≽c}`.

This is the inclusion `c(A) ⊆ c_{≽c}(A)`.
-/
theorem subset_generatedChoiceFromGeneratedPref
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    {A : Set α} {x : α} :
    x ∈ c.choose A → x ∈ (generatedChoiceFromGeneratedPref c).choose A := by
  intro hxA
  constructor
  · exact hFrom A hxA
  · intro y hyA
    by_contra hxNotPair
    have hyPair : y ∈ c.choose ({x, y} : Set α) :=
      other_mem_choose_of_not_mem_choose_pair c hFrom hFN hxNotPair
    have hxNotA : x ∉ c.choose A :=
      hCC
        (by simp)
        (by simp)
        hyA
        (hFrom A hxA)
        hyPair
        hxNotPair
    exact hxNotA hxA

/--
If `c(A)` is nonempty, then every element chosen by `c_{≽c}` from `A`
is also chosen by `c`.
-/
theorem subset_of_generatedChoiceFromGeneratedPref_if_nonempty
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    {A : Set α}
    (hNE : (c.choose A).Nonempty)
    {x : α} :
    x ∈ (generatedChoiceFromGeneratedPref c).choose A → x ∈ c.choose A := by
  let _ := hFN
  intro hxGen
  rcases hNE with ⟨x₀, hx₀A⟩
  have hxPair : x ∈ c.choose ({x, x₀} : Set α) := by
    exact hxGen.2 x₀ (hFrom A hx₀A)
  by_contra hxNotA
  have hxNotPair : x ∉ c.choose ({x, x₀} : Set α) :=
    hCC
      (hFrom A hx₀A)
      hxGen.1
      (by simp)
      (by simp)
      hx₀A
      hxNotA
  exact hxNotPair hxPair

/--
For every feasible set `A`, either `c(A)` is empty or `c(A) = c_{≽c}(A)`.
-/
theorem choose_eq_empty_or_eq_generatedChoiceFromGeneratedPref
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    (A : Set α) :
    c.choose A = ∅ ∨ c.choose A = (generatedChoiceFromGeneratedPref c).choose A := by
  by_cases hNE : (c.choose A).Nonempty
  · right
    apply Set.Subset.antisymm
    · intro x hx
      exact subset_generatedChoiceFromGeneratedPref c hFrom hFN hCC hx
    · intro x hx
      exact subset_of_generatedChoiceFromGeneratedPref_if_nonempty
        c hFrom hFN hCC hNE hx
  · left
    exact Set.not_nonempty_iff_eq_empty.mp hNE

end ChoiceFunction

end EcoLean
