import EcoLean.ChoicePreferenceUtility.Choice
import Mathlib.Data.Set.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Order.Preorder.Finite
import Mathlib.Order.Minimal

universe u

namespace EcoLean

/--
A preference relation on a domain `α`.

The primitive notion is weak preference.
-/
structure Preference (α : Type u) where
  weakPref : α → α → Prop

namespace Preference

variable {α : Type u} (P : Preference α)

/-!
# Derived relations and rationality properties
-/

/-- Strict preference derived from weak preference. -/
def StrictPref (x y : α) : Prop :=
  P.weakPref x y ∧ ¬ P.weakPref y x

/-- Indifference derived from weak preference. -/
def Indiff (x y : α) : Prop :=
  P.weakPref x y ∧ P.weakPref y x

/-- Completeness of weak preference. -/
def Complete : Prop :=
  ∀ x y : α, P.weakPref x y ∨ P.weakPref y x

/-- Transitivity of weak preference. -/
def Transitive : Prop :=
  ∀ x y z : α, P.weakPref x y → P.weakPref y z → P.weakPref x z

scoped notation:50 x " ≽[" P "] " y => Preference.weakPref P x y
scoped notation:50 x " ≻[" P "] " y => Preference.StrictPref P x y
scoped notation:50 x " ∼[" P "] " y => Preference.Indiff P x y

/--
Lemma: completeness implies reflexivity.
-/
theorem weakPref_refl_of_complete
    (hC : P.Complete) (x : α) :
    P.weakPref x x := by
  cases hC x x with
  | inl hxx => exact hxx
  | inr hxx => exact hxx

/--
Definition: the choice function generated by preference maximization.

This is Kreps' formula `c_≽(A) = {x ∈ A : x ≽ y for all y ∈ A}`.
-/
def generatedChoice : ChoiceFunction α where
  choose A := {x : α | x ∈ A ∧ ∀ y : α, y ∈ A → P.weakPref x y}

/--
Lemma: the choice function generated by a preference chooses only from the feasible set.
-/
theorem generatedChoice_choosesFrom :
    (P.generatedChoice).ChoosesFrom := by
  intro A x hx
  exact hx.1

/--
Lemma: if `x` is chosen by preference maximization from `A`,
then `x` is weakly preferred to every feasible alternative in `A`.
-/
theorem weakPref_of_mem_generatedChoice
    {A : Set α} {x y : α}
    (hx : x ∈ (P.generatedChoice).choose A)
    (hy : y ∈ A) :
    P.weakPref x y := by
  exact hx.2 y hy

/--
Theorem: if a preference relation is complete and transitive, then from every
finite nonempty feasible set there exists an element weakly preferred to every
other feasible element.
-/
theorem exists_best_of_finite_of_complete_transitive
    (hC : P.Complete)
    (hT : P.Transitive)
    {A : Set α}
    (hFin : A.Finite)
    (hNE : A.Nonempty) :
    ∃ x : α, x ∈ A ∧ ∀ y : α, y ∈ A → P.weakPref x y := by
  classical
  letI : LE α := ⟨fun a b => P.weakPref b a⟩
  letI : IsTrans α (fun a b => P.weakPref b a) := ⟨by
    intro a b c hab hbc
    exact hT c b a hbc hab
  ⟩

  rcases Set.Finite.exists_maximal (s := A) hFin hNE with ⟨x, hxMax⟩
  have hxA : x ∈ A := hxMax.1

  refine ⟨x, hxA, ?_⟩
  intro y hyA
  by_cases hxy : P.weakPref x y
  · exact hxy
  · have hyx : P.weakPref y x := by
      cases hC x y with
      | inl h =>
          exact False.elim (hxy h)
      | inr h =>
          exact h
    have hNotMax : ¬ Maximal (fun z : α => z ∈ A) x := by
      exact (not_maximal_iff hxA).2 ⟨y, hyA, hyx, hxy⟩
    exact False.elim (hNotMax hxMax)
/--
Theorem: if a preference relation is complete and transitive, then the generated
choice function satisfies choice coherence.
-/
theorem generatedChoice_choiceCoherent
    (hC : P.Complete)
    (hT : P.Transitive) :
    (P.generatedChoice).ChoiceCoherent := by
  let _ := hC
  intro A B x y hxA hyA hxB hyB hxChooseA hyNotChooseA
  have hxy : P.weakPref x y := hxChooseA.2 y hyA

  have hWitness : ∃ z : α, z ∈ A ∧ ¬ P.weakPref y z := by
    by_contra hNo
    apply hyNotChooseA
    constructor
    · exact hyA
    · intro z hz
      by_contra hyz
      exact hNo ⟨z, hz, hyz⟩

  rcases hWitness with ⟨z, hzA, hyNotz⟩

  have hyNotx : ¬ P.weakPref y x := by
    intro hyx
    have hyz : P.weakPref y z := hT y x z hyx (hxChooseA.2 z hzA)
    exact hyNotz hyz

  intro hyChooseB
  have hyxB : P.weakPref y x := hyChooseB.2 x hxB
  exact hyNotx hyxB

/--
Theorem: if a preference relation is complete and transitive, then the generated
choice function satisfies finite nonemptiness.
-/
theorem generatedChoice_finiteNonempty
    (hC : P.Complete)
    (hT : P.Transitive) :
    (P.generatedChoice).FiniteNonempty := by
  intro A hFin hNE
  rcases exists_best_of_finite_of_complete_transitive P hC hT hFin hNE with
    ⟨x, hxA, hxBest⟩
  refine ⟨x, ?_⟩
  constructor
  · exact hxA
  · exact hxBest

end Preference

namespace ChoiceFunction

variable {α : Type u} (c : ChoiceFunction α)

/-!
# Preference generated by pairwise choice
-/

/--
Definition: the preference relation generated by pairwise choice.

Following Kreps, `x ≽_c y` holds if `x ∈ c({x,y})`.
-/
def generatedPref : Preference α where
  weakPref x y := x ∈ c.choose ({x, y} : Set α)

/--
Definition: the choice function generated from the preference induced by `c`.

This is `c_{≽c}` in Kreps.
-/
def generatedChoiceFromGeneratedPref : ChoiceFunction α :=
  (generatedPref c).generatedChoice

/--
Lemma: an equivalent contrapositive form of choice coherence.

If `x` is chosen from `A` and `y` is chosen from `B`, with `x,y` feasible in both,
then `y` must be chosen from `A` and `x` must be chosen from `B`.
-/
theorem choiceCoherent_contrapos
    (hCC : c.ChoiceCoherent)
    {A B : Set α} {x y : α}
    (hxA : x ∈ A) (hyA : y ∈ A)
    (hxB : x ∈ B) (hyB : y ∈ B)
    (hxChooseA : x ∈ c.choose A)
    (hyChooseB : y ∈ c.choose B) :
    y ∈ c.choose A ∧ x ∈ c.choose B := by
  constructor
  · by_contra hyNotA
    exact (hCC hxA hyA hxB hyB hxChooseA hyNotA) hyChooseB
  · by_contra hxNotB
    exact (hCC hyB hxB hyA hxA hyChooseB hxNotB) hxChooseA

/--
Theorem: if `c` satisfies finite nonemptiness and chooses only from feasible sets,
then the preference `≽_c` is complete.
-/
theorem generatedPref_complete
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty) :
    (generatedPref c).Complete := by
  intro x y
  have hNE : (c.choose ({x, y} : Set α)).Nonempty :=
    pair_choice_nonempty c hFN x y
  rcases hNE with ⟨z, hz⟩
  rcases mem_pair_of_mem_choose_pair c hFrom hz with hzx | hzy
  · subst hzx
    exact Or.inl (by simpa [generatedPref] using hz)
  · subst hzy
    exact Or.inr (by simpa [generatedPref, Set.pair_comm] using hz)

/--
Theorem: if `c` satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent, then the preference `≽_c` is transitive.
-/
theorem generatedPref_transitive
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedPref c).Transitive := by
  intro x y z hxy hyz

  let T : Set α := ({x, y, z} : Set α)

  have hTNE : (c.choose T).Nonempty := by
    apply hFN
    ·
      change ({x, y, z} : Set α).Finite
      exact Set.Finite.insert x (Set.Finite.insert y (Set.finite_singleton z))
    ·
      exact ⟨x, by simp [T]⟩

  have hxT : x ∈ c.choose T := by
    by_contra hxNotT

    have hyNotT : y ∉ c.choose T := by
      intro hyT
      have hxNotXY : x ∉ c.choose ({x, y} : Set α) :=
        hCC
          (by simp [T])
          (by simp [T])
          (by simp)
          (by simp)
          hyT
          hxNotT
      exact hxNotXY hxy

    have hzNotT : z ∉ c.choose T := by
      intro hzT
      have hyNotYZ : y ∉ c.choose ({y, z} : Set α) :=
        hCC
          (by simp [T])
          (by simp [T])
          (by simp)
          (by simp)
          hzT
          hyNotT
      exact hyNotYZ hyz

    rcases hTNE with ⟨w, hw⟩
    have hwT : w ∈ T := hFrom T hw
    have hwCases : w = x ∨ w = y ∨ w = z := by
      simpa [T] using hwT
    cases hwCases with
    | inl hwx =>
        subst hwx
        exact hxNotT hw
    | inr hrest =>
        cases hrest with
        | inl hwy =>
            subst hwy
            exact hyNotT hw
        | inr hwz =>
            subst hwz
            exact hzNotT hw

  have hxXZ : x ∈ c.choose ({x, z} : Set α) := by
    by_contra hxNotXZ
    have hzXZ : z ∈ c.choose ({x, z} : Set α) :=
      other_mem_choose_of_not_mem_choose_pair c hFrom hFN hxNotXZ
    have hxNotT' : x ∉ c.choose T :=
      hCC
        (by simp)
        (by simp)
        (by simp [T])
        (by simp [T])
        hzXZ
        hxNotXZ
    exact hxNotT' hxT

  exact hxXZ

/--
Theorem: the preference-generated choice function `c_{≽c}` chooses only from the feasible set.
-/
theorem generatedChoiceFromGeneratedPref_choosesFrom :
    (generatedChoiceFromGeneratedPref c).ChoosesFrom := by
  exact Preference.generatedChoice_choosesFrom (P := generatedPref c)

/--
Theorem: the preference-generated choice function `c_{≽c}` satisfies choice coherence,
provided `c` itself satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent.
-/
theorem generatedChoiceFromGeneratedPref_choiceCoherent
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedChoiceFromGeneratedPref c).ChoiceCoherent := by
  have hComp : (generatedPref c).Complete :=
    generatedPref_complete c hFrom hFN
  have hTrans : (generatedPref c).Transitive :=
    generatedPref_transitive c hFrom hFN hCC
  simpa [generatedChoiceFromGeneratedPref] using
    (Preference.generatedChoice_choiceCoherent
      (P := generatedPref c) hComp hTrans)

/--
Theorem: the preference-generated choice function `c_{≽c}` satisfies finite nonemptiness,
provided `c` itself satisfies finite nonemptiness, chooses only from feasible sets,
and is choice coherent.
-/
theorem generatedChoiceFromGeneratedPref_finiteNonempty
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    (generatedChoiceFromGeneratedPref c).FiniteNonempty := by
  have hComp : (generatedPref c).Complete :=
    generatedPref_complete c hFrom hFN
  have hTrans : (generatedPref c).Transitive :=
    generatedPref_transitive c hFrom hFN hCC
  simpa [generatedChoiceFromGeneratedPref] using
    (Preference.generatedChoice_finiteNonempty
      (P := generatedPref c) hComp hTrans)

/--
Theorem: every element chosen by `c` is also chosen by `c_{≽c}`.

This is the inclusion `c(A) ⊆ c_{≽c}(A)`.
-/
theorem subset_generatedChoiceFromGeneratedPref
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    {A : Set α} {x : α} :
    x ∈ c.choose A → x ∈ (generatedChoiceFromGeneratedPref c).choose A := by
  intro hxA
  constructor
  · exact hFrom A hxA
  · intro y hyA
    by_contra hxNotPair
    have hyPair : y ∈ c.choose ({x, y} : Set α) :=
      other_mem_choose_of_not_mem_choose_pair c hFrom hFN hxNotPair
    have hxNotA : x ∉ c.choose A :=
      hCC
        (by simp)
        (by simp)
        hyA
        (hFrom A hxA)
        hyPair
        hxNotPair
    exact hxNotA hxA

/--
Theorem: if `c(A)` is nonempty, then every element chosen by `c_{≽c}` from `A`
is also chosen by `c`.
-/
theorem subset_of_generatedChoiceFromGeneratedPref_if_nonempty
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    {A : Set α}
    (hNE : (c.choose A).Nonempty)
    {x : α} :
    x ∈ (generatedChoiceFromGeneratedPref c).choose A → x ∈ c.choose A := by
  let _ := hFN
  intro hxGen
  rcases hNE with ⟨x₀, hx₀A⟩
  have hxPair : x ∈ c.choose ({x, x₀} : Set α) := by
    exact hxGen.2 x₀ (hFrom A hx₀A)
  by_contra hxNotA
  have hxNotPair : x ∉ c.choose ({x, x₀} : Set α) :=
    hCC
      (hFrom A hx₀A)
      hxGen.1
      (by simp)
      (by simp)
      hx₀A
      hxNotA
  exact hxNotPair hxPair

/--
Theorem: for every feasible set `A`, either `c(A)` is empty or `c(A) = c_{≽c}(A)`.
-/
theorem choose_eq_empty_or_eq_generatedChoiceFromGeneratedPref
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    (A : Set α) :
    c.choose A = ∅ ∨ c.choose A = (generatedChoiceFromGeneratedPref c).choose A := by
  by_cases hNE : (c.choose A).Nonempty
  · right
    apply Set.Subset.antisymm
    · intro x hx
      exact subset_generatedChoiceFromGeneratedPref c hFrom hFN hCC hx
    · intro x hx
      exact subset_of_generatedChoiceFromGeneratedPref_if_nonempty
        c hFrom hFN hCC hNE hx
  · left
    exact Set.not_nonempty_iff_eq_empty.mp hNE

end ChoiceFunction

end EcoLean
