import EcoLean.ChoicePreferenceUtility.Preference
import Mathlib.Data.Real.Basic
import EcoLean.ChoicePreferenceUtility.NoBetterThan
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Finset.Card

universe u

namespace EcoLean

namespace Utility

variable {α : Type u}

/-!
# Utility functions

This file formalises the Chapter 1 move in Kreps from preference rationalisation
to utility representation.

A utility function can be used in two related ways:

1. It induces a preference relation by numerical comparison.
2. It induces a choice function by utility maximisation over feasible sets.
-/

/-- A utility function on a choice domain `α`. -/
abbrev UtilityFunction (α : Type u) := α → ℝ

/--
Definition: the preference relation induced by a utility function.

This is the preference relation for which `x` is weakly preferred to `y`
exactly when `u x ≥ u y`.
-/
def generatedPref (u : UtilityFunction α) : Preference α where
  weakPref x y := u x ≥ u y

/--
Definition: the choice function induced by a utility function.

The chosen set from `A` consists of all feasible elements in `A`
whose utility is at least as large as that of every other feasible element in `A`.
-/
def generatedChoice (u : UtilityFunction α) : ChoiceFunction α where
  choose A := {x : α | x ∈ A ∧ ∀ y : α, y ∈ A → u x ≥ u y}

/-!
# Basic theorems about the preference generated by a utility function
-/

/--
Theorem: the preference generated by a utility function is complete.
-/
theorem generatedPref_complete
    (u : UtilityFunction α) :
    (generatedPref u).Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr hxy
  | inr hyx =>
      exact Or.inl hyx

/--
Theorem: the preference generated by a utility function is transitive.
-/
theorem generatedPref_transitive
    (u : UtilityFunction α) :
    (generatedPref u).Transitive := by
  intro x y z hxy hyz
  exact le_trans hyz hxy

/--
Theorem: under the utility-generated preference, strict preference
is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 hyx
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact le_of_lt hxy
    · intro hyx
      exact (not_le_of_gt hxy) hyx

/--
Theorem: under the utility-generated preference, indifference
is equivalent to utility equality.
-/
theorem indiff_iff_eq
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    exact le_antisymm hxy.2 hxy.1
  · intro hEq
    constructor
    · change u x ≥ u y
      simpa [hEq]
    · change u y ≥ u x
      simpa [hEq]
/-!
# Basic theorems about the choice function generated by a utility function
-/

/--
Theorem: the utility-generated choice function chooses only from the feasible set.
-/
theorem generatedChoice_choosesFrom
    (u : UtilityFunction α) :
    (generatedChoice u).ChoosesFrom := by
  intro A x hx
  exact hx.1

/--
Lemma: if `x` is chosen by utility maximisation from `A`, then `x` has utility
at least as large as every feasible alternative in `A`.
-/
theorem ge_of_mem_generatedChoice
    (u : UtilityFunction α)
    {A : Set α} {x y : α}
    (hx : x ∈ (generatedChoice u).choose A)
    (hy : y ∈ A) :
    u x ≥ u y := by
  exact hx.2 y hy

/--
Theorem: the choice function generated directly by utility is exactly the choice
function generated from the preference relation induced by that utility.
-/
theorem generatedChoice_eq_generatedChoice_of_generatedPref
    (u : UtilityFunction α) :
    generatedChoice u = (generatedPref u).generatedChoice := by
  rfl
/--
Theorem: the utility-generated choice function satisfies choice coherence.

This follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_choiceCoherent
    (u : UtilityFunction α) :
    (generatedChoice u).ChoiceCoherent := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_choiceCoherent
      (P := generatedPref u) hC hT)

/--
Theorem: the utility-generated choice function satisfies finite nonemptiness.

Again this follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_finiteNonempty
    (u : UtilityFunction α) :
    (generatedChoice u).FiniteNonempty := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_finiteNonempty
      (P := generatedPref u) hC hT)

/--
Definition: a utility function rationalises a choice function if the latter
is exactly the choice function generated by utility maximisation.
-/
def Rationalizes (u : UtilityFunction α) (c : ChoiceFunction α) : Prop :=
  c = generatedChoice u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function chooses only from feasible sets.
-/
theorem choosesFrom_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoosesFrom := by
  subst hRat
  exact generatedChoice_choosesFrom u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function satisfies choice coherence.
-/
theorem choiceCoherent_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoiceCoherent := by
  subst hRat
  exact generatedChoice_choiceCoherent u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function satisfies finite nonemptiness.
-/
theorem finiteNonempty_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.FiniteNonempty := by
  subst hRat
  exact generatedChoice_finiteNonempty u

end Utility

namespace Preference

variable {α : Type u}

/-!
# Utility representation of a preference relation

A utility function represents a preference relation if weak preference
coincides exactly with weak utility comparison.
-/

/--
Definition: a utility function `u` represents a preference relation `P`
if `x ≽ y` holds exactly when `u x ≥ u y`.
-/
def Represents (u : Utility.UtilityFunction α) (P : Preference α) : Prop :=
  ∀ x y : α, P.weakPref x y ↔ u x ≥ u y

/--
Theorem: every utility function represents the preference relation it generates.
-/
theorem generatedPref_is_represented
    (u : Utility.UtilityFunction α) :
    Represents u (Utility.generatedPref u) := by
  intro x y
  rfl

/--
Theorem: if a utility function represents a preference relation, then that
preference relation is complete.
-/
theorem complete_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr ((hRep y x).mpr hxy)
  | inr hyx =>
      exact Or.inl ((hRep x y).mpr hyx)

/--
Theorem: if a utility function represents a preference relation, then that
preference relation is transitive.
-/
theorem transitive_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Transitive := by
  intro x y z hxy hyz
  have hxy' : u x ≥ u y := (hRep x y).mp hxy
  have hyz' : u y ≥ u z := (hRep y z).mp hyz
  have hxz' : u x ≥ u z := le_trans hyz' hxy'
  exact (hRep x z).mpr hxz'

/--
Theorem: if a utility function represents a preference relation, then under that
preference strict preference is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 ((hRep y x).mpr hyx)
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact (hRep x y).mpr (le_of_lt hxy)
    · intro hyx
      have hyx' : u y ≥ u x := (hRep y x).mp hyx
      exact (not_le_of_gt hxy) hyx'

/--
Theorem: if a utility function represents a preference relation, then under that
preference indifference is equivalent to utility equality.
-/
theorem indiff_iff_eq_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    have hxy' : u x ≥ u y := (hRep x y).mp hxy.1
    have hyx' : u y ≥ u x := (hRep y x).mp hxy.2
    exact le_antisymm hyx' hxy'
  · intro hEq
    constructor
    · exact (hRep x y).mpr (by simpa [hEq])
    · exact (hRep y x).mpr (by simpa [hEq])

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation coincides exactly with
the choice function generated directly by utility maximisation.
-/
theorem generatedChoice_eq_generatedChoice_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice = Utility.generatedChoice u := by
  ext A x
  constructor
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mp (hx.2 y hy)
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mpr (hx.2 y hy)

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies choice coherence.
-/
theorem generatedChoice_choiceCoherent_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.ChoiceCoherent := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_choiceCoherent (P := P) hC hT

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies finite nonemptiness.
-/
theorem generatedChoice_finiteNonempty_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.FiniteNonempty := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_finiteNonempty (P := P) hC hT


/-!
# Finite utility representation

On a finite domain, a complete and transitive preference can be represented
by the cardinality of its no-better-than sets.
-/

/--
The finite no-better-than finset of `x`.
-/
noncomputable def noBetterThanFinset
    [Fintype α]
    (P : Preference α) (x : α) : Finset α := by
  classical
  exact Finset.univ.filter (fun y => y ∈ P.NoBetterThan x)

/--
The finite utility attached to a preference on a finite domain.

It assigns to each `x` the number of objects no better than `x`.
-/
noncomputable def finiteUtility
    [Fintype α]
    (P : Preference α) : Utility.UtilityFunction α := by
  classical
  intro x
  exact ((noBetterThanFinset P x).card : ℝ)

/--
Membership in the no-better-than finset is equivalent to weak preference.
-/
theorem mem_noBetterThanFinset_iff
    [Fintype α]
    (P : Preference α) {x y : α} :
    y ∈ noBetterThanFinset P x ↔ y ∈ P.NoBetterThan x := by
  classical
  simp [noBetterThanFinset]

/--
If `x ≽ y`, then the finite utility of `x` is at least as large as that of `y`.
-/
theorem finiteUtility_ge_of_weakPref
    [Fintype α]
    (P : Preference α)
    (hT : P.Transitive) {x y : α}
    (hxy : P.weakPref x y) :
    finiteUtility P x ≥ finiteUtility P y := by
  classical
  have hSub :
      noBetterThanFinset P y ⊆ noBetterThanFinset P x := by
    intro z hz
    have hz' : z ∈ P.NoBetterThan y := by
      exact (mem_noBetterThanFinset_iff P).mp hz
    have hxz : z ∈ P.NoBetterThan x := by
      exact noBetterThan_subset_of_weakPref P hT hxy hz'
    exact (mem_noBetterThanFinset_iff P).mpr hxz
  have hCard :
      (noBetterThanFinset P y).card ≤ (noBetterThanFinset P x).card :=
    Finset.card_le_card hSub
  change ((noBetterThanFinset P x).card : ℝ) ≥ ((noBetterThanFinset P y).card : ℝ)
  exact_mod_cast hCard

/--
If `¬ x ≽ y`, then the finite utility of `x` is strictly smaller than that of `y`.
-/
theorem finiteUtility_lt_of_not_weakPref
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) {x y : α}
    (hNot : ¬ P.weakPref x y) :
    finiteUtility P x < finiteUtility P y := by
  classical
  have hyx : P.weakPref y x := by
    cases hC x y with
    | inl hxy =>
        exact False.elim (hNot hxy)
    | inr hyx =>
        exact hyx

  have hSub :
      noBetterThanFinset P x ⊆ noBetterThanFinset P y := by
    intro z hz
    have hz' : z ∈ P.NoBetterThan x := by
      exact (mem_noBetterThanFinset_iff P).mp hz
    have hyz : z ∈ P.NoBetterThan y := by
      exact noBetterThan_subset_of_weakPref P hT hyx hz'
    exact (mem_noBetterThanFinset_iff P).mpr hyz

  have hNotRev :
      ¬ noBetterThanFinset P y ⊆ noBetterThanFinset P x := by
    intro hRev
    have hyy : y ∈ noBetterThanFinset P y := by
      apply (mem_noBetterThanFinset_iff P).mpr
      exact self_mem_noBetterThan_of_complete P hC y
    have hyx' : y ∈ noBetterThanFinset P x := hRev hyy
    have hxy' : y ∈ P.NoBetterThan x := by
      exact (mem_noBetterThanFinset_iff P).mp hyx'
    exact hNot hxy'

  have hSSub :
      noBetterThanFinset P x ⊂ noBetterThanFinset P y :=
    ⟨hSub, hNotRev⟩

  have hCard :
      (noBetterThanFinset P x).card < (noBetterThanFinset P y).card :=
    Finset.card_lt_card hSSub

  change ((noBetterThanFinset P x).card : ℝ) < ((noBetterThanFinset P y).card : ℝ)
  exact_mod_cast hCard

/--
The finite utility attached to a complete and transitive preference
represents that preference.
-/
theorem finiteUtility_represents
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    Represents (finiteUtility P) P := by
  intro x y
  constructor
  · intro hxy
    exact finiteUtility_ge_of_weakPref P hT hxy
  · intro hxy
    by_cases hxy' : P.weakPref x y
    · exact hxy'
    · have hlt : finiteUtility P x < finiteUtility P y :=
        finiteUtility_lt_of_not_weakPref P hC hT hxy'
      exact False.elim ((not_lt_of_ge hxy) hlt)

/--
Finite utility-existence theorem:

every complete and transitive preference on a finite domain
admits a utility representation.
-/
theorem exists_utility_of_finite_complete_transitive
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    ∃ u : Utility.UtilityFunction α, Represents u P := by
  refine ⟨finiteUtility P, ?_⟩
  exact finiteUtility_represents P hC hT

end Preference

namespace ChoiceFunction

variable {α : Type u}

/--
Finite utility rationalisation of choice:

if a choice function on a finite domain chooses from feasible sets,
satisfies finite nonemptiness, and is choice coherent, then it is
rationalised by a utility function.
-/
theorem exists_utility_rationalizing_choice
    [Fintype α]
    (c : ChoiceFunction α)
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    ∃ u : Utility.UtilityFunction α, c = Utility.generatedChoice u := by
  classical
  let P : Preference α := generatedPref c

  have hComp : P.Complete :=
    generatedPref_complete c hFrom hFN

  have hTrans : P.Transitive :=
    generatedPref_transitive c hFrom hFN hCC

  rcases Preference.exists_utility_of_finite_complete_transitive P hComp hTrans with
    ⟨u, hRep⟩

  have hEqPrefChoice : c = generatedChoiceFromGeneratedPref c := by
    ext A x
    constructor
    · intro hx
      exact subset_generatedChoiceFromGeneratedPref c hFrom hFN hCC hx
    · intro hx
      have hxA : x ∈ A := by
        exact generatedChoiceFromGeneratedPref_choosesFrom (c := c) A hx
      have hCase :=
        choose_eq_empty_or_eq_generatedChoiceFromGeneratedPref c hFrom hFN hCC A
      cases hCase with
      | inl hEmpty =>
          have hFinA : A.Finite := by
            classical
            exact Set.toFinite A
          have hNEA : (c.choose A).Nonempty := hFN hFinA ⟨x, hxA⟩
          simpa [hEmpty] using hNEA
      | inr hEq =>
          simpa [hEq] using hx

  refine ⟨u, ?_⟩
  calc
    c = generatedChoiceFromGeneratedPref c := hEqPrefChoice
    _ = P.generatedChoice := rfl
    _ = Utility.generatedChoice u :=
      Preference.generatedChoice_eq_generatedChoice_of_represents hRep

end ChoiceFunction

end EcoLean
