import EcoLean.ChoicePreferenceUtility.Preference
import Mathlib.Data.Real.Basic

universe u

namespace EcoLean

namespace Utility

variable {α : Type u}

/-!
# Utility functions

This file formalises the Chapter 1 move in Kreps from preference rationalisation
to utility representation.

A utility function can be used in two related ways:

1. It induces a preference relation by numerical comparison.
2. It induces a choice function by utility maximisation over feasible sets.
-/

/-- A utility function on a choice domain `α`. -/
abbrev UtilityFunction (α : Type u) := α → ℝ

/--
Definition: the preference relation induced by a utility function.

This is the preference relation for which `x` is weakly preferred to `y`
exactly when `u x ≥ u y`.
-/
def generatedPref (u : UtilityFunction α) : Preference α where
  weakPref x y := u x ≥ u y

/--
Definition: the choice function induced by a utility function.

The chosen set from `A` consists of all feasible elements in `A`
whose utility is at least as large as that of every other feasible element in `A`.
-/
def generatedChoice (u : UtilityFunction α) : ChoiceFunction α where
  choose A := {x : α | x ∈ A ∧ ∀ y : α, y ∈ A → u x ≥ u y}

/-!
# Basic theorems about the preference generated by a utility function
-/

/--
Theorem: the preference generated by a utility function is complete.
-/
theorem generatedPref_complete
    (u : UtilityFunction α) :
    (generatedPref u).Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr hxy
  | inr hyx =>
      exact Or.inl hyx

/--
Theorem: the preference generated by a utility function is transitive.
-/
theorem generatedPref_transitive
    (u : UtilityFunction α) :
    (generatedPref u).Transitive := by
  intro x y z hxy hyz
  exact le_trans hyz hxy

/--
Theorem: under the utility-generated preference, strict preference
is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 hyx
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact le_of_lt hxy
    · intro hyx
      exact (not_le_of_gt hxy) hyx

/--
Theorem: under the utility-generated preference, indifference
is equivalent to utility equality.
-/
theorem indiff_iff_eq
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    exact le_antisymm hxy.2 hxy.1
  · intro hEq
    constructor
    · change u x ≥ u y
      simpa [hEq]
    · change u y ≥ u x
      simpa [hEq]
/-!
# Basic theorems about the choice function generated by a utility function
-/

/--
Theorem: the utility-generated choice function chooses only from the feasible set.
-/
theorem generatedChoice_choosesFrom
    (u : UtilityFunction α) :
    (generatedChoice u).ChoosesFrom := by
  intro A x hx
  exact hx.1

/--
Lemma: if `x` is chosen by utility maximisation from `A`, then `x` has utility
at least as large as every feasible alternative in `A`.
-/
theorem ge_of_mem_generatedChoice
    (u : UtilityFunction α)
    {A : Set α} {x y : α}
    (hx : x ∈ (generatedChoice u).choose A)
    (hy : y ∈ A) :
    u x ≥ u y := by
  exact hx.2 y hy

/--
Theorem: the choice function generated directly by utility is exactly the choice
function generated from the preference relation induced by that utility.
-/
theorem generatedChoice_eq_generatedChoice_of_generatedPref
    (u : UtilityFunction α) :
    generatedChoice u = (generatedPref u).generatedChoice := by
  rfl
/--
Theorem: the utility-generated choice function satisfies choice coherence.

This follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_choiceCoherent
    (u : UtilityFunction α) :
    (generatedChoice u).ChoiceCoherent := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_choiceCoherent
      (P := generatedPref u) hC hT)

/--
Theorem: the utility-generated choice function satisfies finite nonemptiness.

Again this follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_finiteNonempty
    (u : UtilityFunction α) :
    (generatedChoice u).FiniteNonempty := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_finiteNonempty
      (P := generatedPref u) hC hT)

/--
Definition: a utility function rationalises a choice function if the latter
is exactly the choice function generated by utility maximisation.
-/
def Rationalizes (u : UtilityFunction α) (c : ChoiceFunction α) : Prop :=
  c = generatedChoice u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function chooses only from feasible sets.
-/
theorem choosesFrom_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoosesFrom := by
  subst hRat
  exact generatedChoice_choosesFrom u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function satisfies choice coherence.
-/
theorem choiceCoherent_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoiceCoherent := by
  subst hRat
  exact generatedChoice_choiceCoherent u

/--
Lemma: if a utility function rationalises a choice function, then that choice
function satisfies finite nonemptiness.
-/
theorem finiteNonempty_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.FiniteNonempty := by
  subst hRat
  exact generatedChoice_finiteNonempty u

end Utility

namespace Preference

variable {α : Type u}

/-!
# Utility representation of a preference relation

A utility function represents a preference relation if weak preference
coincides exactly with weak utility comparison.
-/

/--
Definition: a utility function `u` represents a preference relation `P`
if `x ≽ y` holds exactly when `u x ≥ u y`.
-/
def Represents (u : Utility.UtilityFunction α) (P : Preference α) : Prop :=
  ∀ x y : α, P.weakPref x y ↔ u x ≥ u y

/--
Theorem: every utility function represents the preference relation it generates.
-/
theorem generatedPref_is_represented
    (u : Utility.UtilityFunction α) :
    Represents u (Utility.generatedPref u) := by
  intro x y
  rfl

/--
Theorem: if a utility function represents a preference relation, then that
preference relation is complete.
-/
theorem complete_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr ((hRep y x).mpr hxy)
  | inr hyx =>
      exact Or.inl ((hRep x y).mpr hyx)

/--
Theorem: if a utility function represents a preference relation, then that
preference relation is transitive.
-/
theorem transitive_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Transitive := by
  intro x y z hxy hyz
  have hxy' : u x ≥ u y := (hRep x y).mp hxy
  have hyz' : u y ≥ u z := (hRep y z).mp hyz
  have hxz' : u x ≥ u z := le_trans hyz' hxy'
  exact (hRep x z).mpr hxz'

/--
Theorem: if a utility function represents a preference relation, then under that
preference strict preference is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 ((hRep y x).mpr hyx)
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact (hRep x y).mpr (le_of_lt hxy)
    · intro hyx
      have hyx' : u y ≥ u x := (hRep y x).mp hyx
      exact (not_le_of_gt hxy) hyx'

/--
Theorem: if a utility function represents a preference relation, then under that
preference indifference is equivalent to utility equality.
-/
theorem indiff_iff_eq_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    have hxy' : u x ≥ u y := (hRep x y).mp hxy.1
    have hyx' : u y ≥ u x := (hRep y x).mp hxy.2
    exact le_antisymm hyx' hxy'
  · intro hEq
    constructor
    · exact (hRep x y).mpr (by simpa [hEq])
    · exact (hRep y x).mpr (by simpa [hEq])

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation coincides exactly with
the choice function generated directly by utility maximisation.
-/
theorem generatedChoice_eq_generatedChoice_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice = Utility.generatedChoice u := by
  ext A x
  constructor
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mp (hx.2 y hy)
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mpr (hx.2 y hy)

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies choice coherence.
-/
theorem generatedChoice_choiceCoherent_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.ChoiceCoherent := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_choiceCoherent (P := P) hC hT

/--
Theorem: if a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies finite nonemptiness.
-/
theorem generatedChoice_finiteNonempty_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.FiniteNonempty := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_finiteNonempty (P := P) hC hT

end Preference

end EcoLean
