import EcoLean.ChoicePreferenceUtility.Preference
import Mathlib.Data.Real.Basic
import EcoLean.ChoicePreferenceUtility.NoBetterThan
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Finset.Card
import Mathlib.Logic.Encodable.Basic
import Mathlib.Topology.Algebra.InfiniteSum.ENNReal
import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.Algebra.InfiniteSum.Ring
import Mathlib.Topology.Instances.NNReal.Lemmas
import Mathlib.Order.Monotone.Basic

universe u

namespace EcoLean

namespace Utility

variable {α : Type u}

/-!
### Utility functions

This file formalises the Chapter 1 move in Kreps from preference rationalisation
to utility representation. It treats both the finite and encodable cases,
connects preferences and choice functions to utility, and records the
ordinal invariance of utility representation under strictly increasing
transformations.

A utility function can be used in two related ways:

1. It induces a preference relation by numerical comparison.
2. It induces a choice function by utility maximisation over feasible sets.
-/

/-- A utility function on a choice domain `α`. -/
abbrev UtilityFunction (α : Type u) := α → ℝ

/--
The preference relation induced by a utility function.

This is the preference relation for which `x` is weakly preferred to `y`
exactly when `u x ≥ u y`.
-/
def generatedPref (u : UtilityFunction α) : Preference α where
  weakPref x y := u x ≥ u y

/--
The choice function induced by a utility function.

The chosen set from `A` consists of all feasible elements in `A`
whose utility is at least as large as that of every other feasible element in `A`.
-/
def generatedChoice (u : UtilityFunction α) : ChoiceFunction α where
  choose A := {x : α | x ∈ A ∧ ∀ y : α, y ∈ A → u x ≥ u y}

/-! ### Basic theorems about the preference generated by a utility function -/

/-- The preference generated by a utility function is complete. -/
theorem generatedPref_complete
    (u : UtilityFunction α) :
    (generatedPref u).Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr hxy
  | inr hyx =>
      exact Or.inl hyx

/-- The preference generated by a utility function is transitive. -/
theorem generatedPref_transitive
    (u : UtilityFunction α) :
    (generatedPref u).Transitive := by
  intro x y z hxy hyz
  exact le_trans hyz hxy

/--
Under the utility-generated preference, strict preference
is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 hyx
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact le_of_lt hxy
    · intro hyx
      exact (not_le_of_gt hxy) hyx

/--
Under the utility-generated preference, indifference
is equivalent to utility equality.
-/
theorem indiff_iff_eq
    (u : UtilityFunction α) (x y : α) :
    (generatedPref u).Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    exact le_antisymm hxy.2 hxy.1
  · intro hEq
    constructor
    · change u x ≥ u y
      simp [hEq]
    · change u y ≥ u x
      simp [hEq]
/-! ### Basic theorems about the choice function generated by a utility function -/

/-- The utility-generated choice function chooses only from the feasible set. -/
theorem generatedChoice_choosesFrom
    (u : UtilityFunction α) :
    (generatedChoice u).ChoosesFrom := by
  intro A x hx
  exact hx.1

/--
If `x` is chosen by utility maximisation from `A`, then `x` has utility
at least as large as every feasible alternative in `A`.
-/
theorem ge_of_mem_generatedChoice
    (u : UtilityFunction α)
    {A : Set α} {x y : α}
    (hx : x ∈ (generatedChoice u).choose A)
    (hy : y ∈ A) :
    u x ≥ u y := by
  exact hx.2 y hy

/--
The choice function generated directly by utility is exactly the choice
function generated from the preference relation induced by that utility.
-/
theorem generatedChoice_eq_generatedChoice_of_generatedPref
    (u : UtilityFunction α) :
    generatedChoice u = (generatedPref u).generatedChoice := by
  rfl
/--
The utility-generated choice function satisfies choice coherence.

This follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_choiceCoherent
    (u : UtilityFunction α) :
    (generatedChoice u).ChoiceCoherent := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_choiceCoherent
      (P := generatedPref u) hC hT)

/--
The utility-generated choice function satisfies finite nonemptiness.

Again this follows because it coincides with the choice function generated by a
complete and transitive preference relation.
-/
theorem generatedChoice_finiteNonempty
    (u : UtilityFunction α) :
    (generatedChoice u).FiniteNonempty := by
  have hC : (generatedPref u).Complete :=
    generatedPref_complete u
  have hT : (generatedPref u).Transitive :=
    generatedPref_transitive u
  simpa [generatedChoice_eq_generatedChoice_of_generatedPref u] using
    (Preference.generatedChoice_finiteNonempty
      (P := generatedPref u) hC hT)

/--
A utility function rationalises a choice function if the latter
is exactly the choice function generated by utility maximisation.
-/
def Rationalizes (u : UtilityFunction α) (c : ChoiceFunction α) : Prop :=
  c = generatedChoice u

/--
If a utility function rationalises a choice function, then that choice
function chooses only from feasible sets.
-/
theorem choosesFrom_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoosesFrom := by
  subst hRat
  exact generatedChoice_choosesFrom u

/--
If a utility function rationalises a choice function, then that choice
function satisfies choice coherence.
-/
theorem choiceCoherent_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.ChoiceCoherent := by
  subst hRat
  exact generatedChoice_choiceCoherent u

/--
If a utility function rationalises a choice function, then that choice
function satisfies finite nonemptiness.
-/
theorem finiteNonempty_of_rationalizes
    {u : UtilityFunction α} {c : ChoiceFunction α}
    (hRat : Rationalizes u c) :
    c.FiniteNonempty := by
  subst hRat
  exact generatedChoice_finiteNonempty u

end Utility

namespace Preference

variable {α : Type u}

/-!
### Utility representation of a preference relation

A utility function represents a preference relation if weak preference
coincides exactly with weak utility comparison.
-/

/--
A utility function `u` represents a preference relation `P`
if `x ≽ y` holds exactly when `u x ≥ u y`.
-/
def Represents (u : Utility.UtilityFunction α) (P : Preference α) : Prop :=
  ∀ x y : α, P.weakPref x y ↔ u x ≥ u y

/-- Every utility function represents the preference relation it generates. -/
theorem generatedPref_is_represented
    (u : Utility.UtilityFunction α) :
    Represents u (Utility.generatedPref u) := by
  intro x y
  rfl

/--
If a utility function represents a preference relation, then that
preference relation is complete.
-/
theorem complete_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Complete := by
  intro x y
  cases le_total (u x) (u y) with
  | inl hxy =>
      exact Or.inr ((hRep y x).mpr hxy)
  | inr hyx =>
      exact Or.inl ((hRep x y).mpr hyx)

/--
If a utility function represents a preference relation, then that
preference relation is transitive.
-/
theorem transitive_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.Transitive := by
  intro x y z hxy hyz
  have hxy' : u x ≥ u y := (hRep x y).mp hxy
  have hyz' : u y ≥ u z := (hRep y z).mp hyz
  have hxz' : u x ≥ u z := le_trans hyz' hxy'
  exact (hRep x z).mpr hxz'

/--
If a utility function represents a preference relation, then strict preference
under that preference is equivalent to strict utility inequality.
-/
theorem strictPref_iff_gt_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.StrictPref x y ↔ u x > u y := by
  constructor
  · intro hxy
    have hyx_not : ¬ u y ≥ u x := by
      intro hyx
      exact hxy.2 ((hRep y x).mpr hyx)
    have hlt : u y < u x := lt_of_not_ge hyx_not
    simpa using hlt
  · intro hxy
    constructor
    · exact (hRep x y).mpr (le_of_lt hxy)
    · intro hyx
      have hyx' : u y ≥ u x := (hRep y x).mp hyx
      exact (not_le_of_gt hxy) hyx'

/--
If a utility function represents a preference relation, then indifference
under that preference is equivalent to utility equality.
-/
theorem indiff_iff_eq_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) (x y : α) :
    P.Indiff x y ↔ u x = u y := by
  constructor
  · intro hxy
    have hxy' : u x ≥ u y := (hRep x y).mp hxy.1
    have hyx' : u y ≥ u x := (hRep y x).mp hxy.2
    exact le_antisymm hyx' hxy'
  · intro hEq
    constructor
    · exact (hRep x y).mpr (by simp [hEq])
    · exact (hRep y x).mpr (by simp [hEq])

/--
If a utility function represents a preference relation, then the
choice function generated by that preference relation coincides exactly with
the choice function generated directly by utility maximisation.
-/
theorem generatedChoice_eq_generatedChoice_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice = Utility.generatedChoice u := by
  ext A x
  constructor
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mp (hx.2 y hy)
  · intro hx
    constructor
    · exact hx.1
    · intro y hy
      exact (hRep x y).mpr (hx.2 y hy)

/--
If a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies choice coherence.
-/
theorem generatedChoice_choiceCoherent_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.ChoiceCoherent := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_choiceCoherent (P := P) hC hT

/--
If a utility function represents a preference relation, then the
choice function generated by that preference relation satisfies finite nonemptiness.
-/
theorem generatedChoice_finiteNonempty_of_represents
    {u : Utility.UtilityFunction α} {P : Preference α}
    (hRep : Represents u P) :
    P.generatedChoice.FiniteNonempty := by
  have hC : P.Complete := complete_of_represents hRep
  have hT : P.Transitive := transitive_of_represents hRep
  exact Preference.generatedChoice_finiteNonempty (P := P) hC hT


/-!
### Finite utility representation

On a finite domain, a complete and transitive preference can be represented
by the cardinality of its no-better-than sets.
-/

/--
The finite no-better-than finset of `x`.
-/
noncomputable def noBetterThanFinset
    [Fintype α]
    (P : Preference α) (x : α) : Finset α := by
  classical
  exact Finset.univ.filter (fun y => y ∈ P.NoBetterThan x)

/--
The finite utility attached to a preference on a finite domain.

It assigns to each `x` the number of objects no better than `x`.
-/
noncomputable def finiteUtility
    [Fintype α]
    (P : Preference α) : Utility.UtilityFunction α := by
  classical
  intro x
  exact ((noBetterThanFinset P x).card : ℝ)

/--
Membership in the no-better-than finset is equivalent to weak preference.
-/
theorem mem_noBetterThanFinset_iff
    [Fintype α]
    (P : Preference α) {x y : α} :
    y ∈ noBetterThanFinset P x ↔ y ∈ P.NoBetterThan x := by
  classical
  simp [noBetterThanFinset]

/--
If `x ≽ y`, then the finite utility of `x` is at least as large as that of `y`.
-/
theorem finiteUtility_ge_of_weakPref
    [Fintype α]
    (P : Preference α)
    (hT : P.Transitive) {x y : α}
    (hxy : P.weakPref x y) :
    finiteUtility P x ≥ finiteUtility P y := by
  classical
  have hSub :
      noBetterThanFinset P y ⊆ noBetterThanFinset P x := by
    intro z hz
    have hz' : z ∈ P.NoBetterThan y := by
      exact (mem_noBetterThanFinset_iff P).mp hz
    have hxz : z ∈ P.NoBetterThan x := by
      exact noBetterThan_subset_of_weakPref P hT hxy hz'
    exact (mem_noBetterThanFinset_iff P).mpr hxz
  have hCard :
      (noBetterThanFinset P y).card ≤ (noBetterThanFinset P x).card :=
    Finset.card_le_card hSub
  change ((noBetterThanFinset P x).card : ℝ) ≥ ((noBetterThanFinset P y).card : ℝ)
  exact_mod_cast hCard

/--
If `¬ x ≽ y`, then the finite utility of `x` is strictly smaller than that of `y`.
-/
theorem finiteUtility_lt_of_not_weakPref
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) {x y : α}
    (hNot : ¬ P.weakPref x y) :
    finiteUtility P x < finiteUtility P y := by
  classical
  have hyx : P.weakPref y x := by
    cases hC x y with
    | inl hxy =>
        exact False.elim (hNot hxy)
    | inr hyx =>
        exact hyx

  have hSub :
      noBetterThanFinset P x ⊆ noBetterThanFinset P y := by
    intro z hz
    have hz' : z ∈ P.NoBetterThan x := by
      exact (mem_noBetterThanFinset_iff P).mp hz
    have hyz : z ∈ P.NoBetterThan y := by
      exact noBetterThan_subset_of_weakPref P hT hyx hz'
    exact (mem_noBetterThanFinset_iff P).mpr hyz

  have hNotRev :
      ¬ noBetterThanFinset P y ⊆ noBetterThanFinset P x := by
    intro hRev
    have hyy : y ∈ noBetterThanFinset P y := by
      apply (mem_noBetterThanFinset_iff P).mpr
      exact self_mem_noBetterThan_of_complete P hC y
    have hyx' : y ∈ noBetterThanFinset P x := hRev hyy
    have hxy' : y ∈ P.NoBetterThan x := by
      exact (mem_noBetterThanFinset_iff P).mp hyx'
    exact hNot hxy'

  have hSSub :
      noBetterThanFinset P x ⊂ noBetterThanFinset P y :=
    ⟨hSub, hNotRev⟩

  have hCard :
      (noBetterThanFinset P x).card < (noBetterThanFinset P y).card :=
    Finset.card_lt_card hSSub

  change ((noBetterThanFinset P x).card : ℝ) < ((noBetterThanFinset P y).card : ℝ)
  exact_mod_cast hCard

/--
The finite utility attached to a complete and transitive preference
represents that preference.
-/
theorem finiteUtility_represents
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    Represents (finiteUtility P) P := by
  intro x y
  constructor
  · intro hxy
    exact finiteUtility_ge_of_weakPref P hT hxy
  · intro hxy
    by_cases hxy' : P.weakPref x y
    · exact hxy'
    · have hlt : finiteUtility P x < finiteUtility P y :=
        finiteUtility_lt_of_not_weakPref P hC hT hxy'
      exact False.elim ((not_lt_of_ge hxy) hlt)

/--
Finite utility-existence theorem:

every complete and transitive preference on a finite domain
admits a utility representation.
-/
theorem exists_utility_of_finite_complete_transitive
    [Fintype α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    ∃ u : Utility.UtilityFunction α, Represents u P := by
  refine ⟨finiteUtility P, ?_⟩
  exact finiteUtility_represents P hC hT

end Preference

namespace ChoiceFunction

variable {α : Type u}


/--
Finite utility rationalisation of choice:

if a choice function on a finite domain chooses from feasible sets,
satisfies finite nonemptiness, and is choice coherent, then it is
rationalised by a utility function.
-/
theorem exists_utility_rationalizing_choice
    [Fintype α]
    (c : ChoiceFunction α)
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    ∃ u : Utility.UtilityFunction α, c = Utility.generatedChoice u := by
  classical
  let P : Preference α := generatedPref c

  have hComp : P.Complete :=
    generatedPref_complete c hFrom hFN

  have hTrans : P.Transitive :=
    generatedPref_transitive c hFrom hFN hCC

  rcases Preference.exists_utility_of_finite_complete_transitive P hComp hTrans with
    ⟨u, hRep⟩

  have hEqPrefChoice : c = generatedChoiceFromGeneratedPref c := by
    ext A x
    constructor
    · intro hx
      exact subset_generatedChoiceFromGeneratedPref c hFrom hFN hCC hx
    · intro hx
      have hxA : x ∈ A := by
        exact generatedChoiceFromGeneratedPref_choosesFrom (c := c) A hx
      have hCase :=
        choose_eq_empty_or_eq_generatedChoiceFromGeneratedPref c hFrom hFN hCC A
      cases hCase with
      | inl hEmpty =>
          have hFinA : A.Finite := by
            classical
            exact Set.toFinite A
          have hNEA : (c.choose A).Nonempty := hFN hFinA ⟨x, hxA⟩
          simp [hEmpty] at hNEA
      | inr hEq =>
          simpa [hEq] using hx

  refine ⟨u, ?_⟩
  calc
    c = generatedChoiceFromGeneratedPref c := hEqPrefChoice
    _ = P.generatedChoice := rfl
    _ = Utility.generatedChoice u :=
      Preference.generatedChoice_eq_generatedChoice_of_represents hRep

end ChoiceFunction


/-!
### Countable utility representation

For the countable case, it is cleaner to index the utility sum by `ℕ`
using `Encodable.decode`, rather than summing directly over `α`.
-/

namespace Preference

variable {α : Type u}

/--
The dyadic weight attached to index `n`.
-/
noncomputable def dyadicWeightNat (n : ℕ) : NNReal :=
  (1 / 2 : NNReal) ^ (n + 1)

/--
The `n`-th summand in the countable utility of `x`.

If `n` does not decode to an element of `α`, the summand is zero.
If `n` decodes to some `z`, then the summand is the dyadic weight at `n`
precisely when `x ≽ z`.
-/
noncomputable def countableSummandNat
    [Encodable α]
    (P : Preference α) (x : α) (n : ℕ) : NNReal := by
  classical
  match (Encodable.decode n : Option α) with
  | none => exact 0
  | some z =>
      exact if P.weakPref x z then dyadicWeightNat n else 0

/--
The `NNReal`-valued countable utility attached to a preference.
-/
noncomputable def countableUtilityNNReal
    [Encodable α]
    (P : Preference α) : α → NNReal :=
  fun x => ∑' n : ℕ, countableSummandNat P x n

/--
The real-valued countable utility attached to a preference.
-/
noncomputable def countableUtility
    [Encodable α]
    (P : Preference α) : Utility.UtilityFunction α :=
  fun x => (countableUtilityNNReal P x : ℝ)

/-!
### Basic lemmas about the dyadic-weight construction
-/

/-- Dyadic weights are strictly positive. -/
theorem dyadicWeightNat_pos (n : ℕ) :
    0 < dyadicWeightNat n := by
  unfold dyadicWeightNat
  positivity

/-- Dyadic weights are nonzero. -/
theorem dyadicWeightNat_ne_zero (n : ℕ) :
    dyadicWeightNat n ≠ 0 := by
  exact ne_of_gt (dyadicWeightNat_pos n)

/--
If `n` decodes to `z` and `x ≽ z`, then the `n`-th summand for `x`
is exactly the dyadic weight at `n`.
-/
theorem countableSummandNat_eq_weight_of_decode_some_of_weakPref
    [Encodable α]
    (P : Preference α) {x z : α} {n : ℕ}
    (hDec : (Encodable.decode n : Option α) = some z)
    (hxz : P.weakPref x z) :
    countableSummandNat P x n = dyadicWeightNat n := by
  classical
  unfold countableSummandNat
  rw [hDec]
  simp [hxz]

/--
If `n` decodes to `z` and `¬ x ≽ z`, then the `n`-th summand for `x` is zero.
-/
theorem countableSummandNat_eq_zero_of_decode_some_of_not_weakPref
    [Encodable α]
    (P : Preference α) {x z : α} {n : ℕ}
    (hDec : (Encodable.decode n : Option α) = some z)
    (hxz : ¬ P.weakPref x z) :
    countableSummandNat P x n = 0 := by
  classical
  unfold countableSummandNat
  rw [hDec]
  simp [hxz]

/--
If `n` does not decode to any element, then the `n`-th summand is zero.
-/
theorem countableSummandNat_eq_zero_of_decode_none
    [Encodable α]
    (P : Preference α) {x : α} {n : ℕ}
    (hDec : (Encodable.decode n : Option α) = none) :
    countableSummandNat P x n = 0 := by
  classical
  unfold countableSummandNat
  rw [hDec]

/--
Every `n`-th summand is bounded above by the dyadic weight at `n`.
-/
theorem countableSummandNat_le_dyadicWeightNat
    [Encodable α]
    (P : Preference α) (x : α) (n : ℕ) :
    countableSummandNat P x n ≤ dyadicWeightNat n := by
  classical
  cases hDec : (Encodable.decode n : Option α) with
  | none =>
      simp [countableSummandNat, hDec]
  | some z =>
      by_cases hxz : P.weakPref x z
      · simp [countableSummandNat, hDec, hxz]
      · simp [countableSummandNat, hDec, hxz]

/--
If `x ≽ y`, then for every `n`, the `n`-th summand for `y`
is bounded above by the `n`-th summand for `x`.
-/
theorem countableSummandNat_le_of_weakPref
    [Encodable α]
    (P : Preference α)
    (hT : P.Transitive) {x y : α}
    (hxy : P.weakPref x y) :
    ∀ n : ℕ, countableSummandNat P y n ≤ countableSummandNat P x n := by
  intro n
  classical
  cases hDec : (Encodable.decode n : Option α) with
  | none =>
      simp [countableSummandNat, hDec]
  | some z =>
      by_cases hyz : P.weakPref y z
      · have hxz : P.weakPref x z := hT x y z hxy hyz
        simp [countableSummandNat, hDec, hyz, hxz]
      · by_cases hxz : P.weakPref x z
        · simp [countableSummandNat, hDec, hyz, hxz]
        · simp [countableSummandNat, hDec, hyz, hxz]

/--
If `¬ x ≽ y`, then at the specific index encoding `y`, the summand for `x`
is strictly smaller than the summand for `y`.
-/
theorem countableSummandNat_lt_at_encode_of_not_weakPref
    [Encodable α]
    (P : Preference α)
    (hC : P.Complete) {x y : α}
    (hNot : ¬ P.weakPref x y) :
    countableSummandNat P x (Encodable.encode y) <
      countableSummandNat P y (Encodable.encode y) := by
  classical
  have hDec : (Encodable.decode (Encodable.encode y) : Option α) = some y :=
    Encodable.encodek y
  have hyy : P.weakPref y y := weakPref_refl_of_complete P hC y
  rw [countableSummandNat_eq_zero_of_decode_some_of_not_weakPref P hDec hNot]
  rw [countableSummandNat_eq_weight_of_decode_some_of_weakPref P hDec hyy]
  exact dyadicWeightNat_pos (Encodable.encode y)

/-!
### Summability and representation in the countable case
-/

/-- The dyadic-weight series is summable. -/

theorem summable_dyadicWeightNat :
    Summable dyadicWeightNat := by
  let r : NNReal := (1 / 2 : NNReal)
  have hr : r < 1 := by
    dsimp [r]
    norm_num
  have hgeom : Summable (fun n : ℕ => r ^ n) := by
    exact NNReal.summable_geometric hr
  have hmul : Summable (fun n : ℕ => r ^ n * r) := by
    exact hgeom.mul_right r
  unfold dyadicWeightNat
  dsimp [r] at hmul ⊢
  convert hmul using 1

/--
For each `x`, the summand family defining the countable utility is summable.
-/
theorem summable_countableSummandNat
    [Encodable α]
    (P : Preference α) (x : α) :
    Summable (countableSummandNat P x) := by
  exact NNReal.summable_of_le
    (f := dyadicWeightNat)
    (g := countableSummandNat P x)
    (by
      intro n
      exact countableSummandNat_le_dyadicWeightNat P x n)
    summable_dyadicWeightNat
/--
If `x ≽ y`, then the countable utility of `x` is at least as large as that of `y`.
-/
theorem countableUtility_ge_of_weakPref
    [Encodable α]
    (P : Preference α)
    (hT : P.Transitive) {x y : α}
    (hxy : P.weakPref x y) :
    countableUtility P x ≥ countableUtility P y := by
  have hNN :
      countableUtilityNNReal P y ≤ countableUtilityNNReal P x := by
    unfold countableUtilityNNReal
    exact Summable.tsum_le_tsum
      (countableSummandNat_le_of_weakPref (P := P) hT (x := x) (y := y) hxy)
      (summable_countableSummandNat P y)
      (summable_countableSummandNat P x)
  change ((countableUtilityNNReal P x : NNReal) : ℝ) ≥
      ((countableUtilityNNReal P y : NNReal) : ℝ)
  exact_mod_cast hNN

/--
If `¬ x ≽ y`, then the countable utility of `x` is strictly smaller than that of `y`.
-/
theorem countableUtility_lt_of_not_weakPref
    [Encodable α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) {x y : α}
    (hNot : ¬ P.weakPref x y) :
    countableUtility P x < countableUtility P y := by
  have hyx : P.weakPref y x := by
    rcases hC x y with hxy | hyx
    · exact False.elim (hNot hxy)
    · exact hyx
  have hle :
      ∀ n : ℕ, countableSummandNat P x n ≤ countableSummandNat P y n := by
    simpa using
      (countableSummandNat_le_of_weakPref (P := P) hT (x := y) (y := x) hyx)
  have hlt :
      countableSummandNat P x (Encodable.encode y) <
        countableSummandNat P y (Encodable.encode y) := by
    exact countableSummandNat_lt_at_encode_of_not_weakPref P hC hNot
  have hNN :
      countableUtilityNNReal P x < countableUtilityNNReal P y := by
    unfold countableUtilityNNReal
    exact NNReal.tsum_lt_tsum
      hle
      hlt
      (summable_countableSummandNat P y)
  change ((countableUtilityNNReal P x : NNReal) : ℝ) <
      ((countableUtilityNNReal P y : NNReal) : ℝ)
  exact_mod_cast hNN

/--
The countable utility attached to a complete and transitive preference
represents that preference.
-/
theorem countableUtility_represents
    [Encodable α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    Represents (countableUtility P) P := by
  intro x y
  constructor
  · intro hxy
    exact countableUtility_ge_of_weakPref P hT hxy
  · intro hxy
    by_cases hxy' : P.weakPref x y
    · exact hxy'
    · have hlt : countableUtility P x < countableUtility P y :=
        countableUtility_lt_of_not_weakPref P hC hT hxy'
      exact False.elim ((not_lt_of_ge hxy) hlt)

/--
Countable utility-existence theorem:

every complete and transitive preference on an encodable domain
admits a utility representation.
-/
theorem exists_utility_of_encodable_complete_transitive
    [Encodable α]
    (P : Preference α)
    (hC : P.Complete)
    (hT : P.Transitive) :
    ∃ u : Utility.UtilityFunction α, Represents u P := by
  refine ⟨countableUtility P, ?_⟩
  exact countableUtility_represents P hC hT



end Preference

namespace Utility

variable {α : Type u}

/-!
### Ordinal invariance and finite-menu rationalisation
-/

/--
A utility function rationalises a choice function on finite menus if, for every
finite feasible set `A`, the choice from `A` coincides with utility maximisation.
-/
def RationalizesOnFinite
    (u : UtilityFunction α) (c : ChoiceFunction α) : Prop :=
  ∀ A : Set α, A.Finite → c.choose A = (generatedChoice u).choose A

/--
Strictly increasing transformations preserve the utility-generated preference.
-/
theorem generatedPref_eq_generatedPref_comp_strictMono
    (u : UtilityFunction α)
    {φ : ℝ → ℝ}
    (hφ : StrictMono φ) :
    generatedPref (fun x => φ (u x)) = generatedPref u := by
  unfold generatedPref
  simp only [Preference.mk.injEq]
  funext x y
  apply propext
  change φ (u y) ≤ φ (u x) ↔ u y ≤ u x
  simpa using (hφ.le_iff_le (a := u y) (b := u x))
/--
Strictly increasing transformations preserve the utility-generated choice function.
-/
theorem generatedChoice_eq_generatedChoice_comp_strictMono
    (u : UtilityFunction α)
    {φ : ℝ → ℝ}
    (hφ : StrictMono φ) :
    generatedChoice (fun x => φ (u x)) = generatedChoice u := by
  rw [generatedChoice_eq_generatedChoice_of_generatedPref,
      generatedChoice_eq_generatedChoice_of_generatedPref,
      generatedPref_eq_generatedPref_comp_strictMono u hφ]

/--
If `u` rationalises `c`, then every strictly increasing transformation of `u`
also rationalises `c`.
-/
theorem rationalizes_comp_strictMono
    {u : UtilityFunction α} {c : ChoiceFunction α}
    {φ : ℝ → ℝ}
    (hRat : Rationalizes u c)
    (hφ : StrictMono φ) :
    Rationalizes (fun x => φ (u x)) c := by
  rw [Rationalizes] at hRat ⊢
  calc
    c = generatedChoice u := hRat
    _ = generatedChoice (fun x => φ (u x)) := by
      symm
      exact generatedChoice_eq_generatedChoice_comp_strictMono u hφ

/--
If `u` rationalises `c` on finite menus, then every strictly increasing
transformation of `u` also rationalises `c` on finite menus.
-/
theorem rationalizesOnFinite_comp_strictMono
    {u : UtilityFunction α} {c : ChoiceFunction α}
    {φ : ℝ → ℝ}
    (hRat : RationalizesOnFinite u c)
    (hφ : StrictMono φ) :
    RationalizesOnFinite (fun x => φ (u x)) c := by
  intro A hAFin
  rw [hRat A hAFin, generatedChoice_eq_generatedChoice_comp_strictMono u hφ]

end Utility

namespace Preference

variable {α : Type u}

/-!
### Ordinal invariance and chapter summary theorems
-/

/--
Strictly increasing transformations preserve utility representation.
-/
theorem represents_comp_strictMono
    {u : Utility.UtilityFunction α} {P : Preference α}
    {φ : ℝ → ℝ}
    (hRep : Represents u P)
    (hφ : StrictMono φ) :
    Represents (fun x => φ (u x)) P := by
  intro x y
  rw [hRep x y]
  simpa [ge_iff_le] using
    (hφ.le_iff_le (a := u y) (b := u x)).symm
/--
Finite-domain summary theorem:
a preference admits a utility representation if and only if it is complete and transitive.
-/
theorem exists_represents_iff_complete_transitive_finite
    [Fintype α]
    (P : Preference α) :
    (∃ u : Utility.UtilityFunction α, Represents u P) ↔
      P.Complete ∧ P.Transitive := by
  constructor
  · rintro ⟨u, hRep⟩
    exact ⟨complete_of_represents hRep, transitive_of_represents hRep⟩
  · rintro ⟨hC, hT⟩
    exact exists_utility_of_finite_complete_transitive P hC hT

/--
Encodable-domain summary theorem:
a preference admits a utility representation if and only if it is complete and transitive.
-/
theorem exists_represents_iff_complete_transitive_encodable
    [Encodable α]
    (P : Preference α) :
    (∃ u : Utility.UtilityFunction α, Represents u P) ↔
      P.Complete ∧ P.Transitive := by
  constructor
  · rintro ⟨u, hRep⟩
    exact ⟨complete_of_represents hRep, transitive_of_represents hRep⟩
  · rintro ⟨hC, hT⟩
    exact exists_utility_of_encodable_complete_transitive P hC hT

end Preference

namespace ChoiceFunction

variable {α : Type u}

/-!
### Finite-menu utility rationalisation on encodable domains
-/

/--
On every finite menu, a coherent choice function coincides with the choice
induced by its generated preference.
-/
theorem choose_eq_generatedChoiceFromGeneratedPref_of_finite
    (c : ChoiceFunction α)
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent)
    {A : Set α}
    (hAFin : A.Finite) :
    c.choose A = (generatedChoiceFromGeneratedPref c).choose A := by
  ext x
  constructor
  · intro hx
    exact subset_generatedChoiceFromGeneratedPref c hFrom hFN hCC hx
  · intro hx
    have hxA : x ∈ A := by
      exact generatedChoiceFromGeneratedPref_choosesFrom (c := c) A hx
    have hCase :=
      choose_eq_empty_or_eq_generatedChoiceFromGeneratedPref c hFrom hFN hCC A
    cases hCase with
    | inl hEmpty =>
        have hNE : (c.choose A).Nonempty := hFN hAFin ⟨x, hxA⟩
        simp [hEmpty] at hNE
    | inr hEq =>
        simpa [hEq] using hx

/--
Encodable finite-menu utility rationalisation of choice.

On an encodable domain, a coherent choice function is rationalised by a utility
function on every finite feasible menu.
-/
theorem exists_utility_rationalizing_choice_on_finite_sets
    [Encodable α]
    (c : ChoiceFunction α)
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    ∃ u : Utility.UtilityFunction α, Utility.RationalizesOnFinite u c := by
  classical
  let P : Preference α := generatedPref c

  have hComp : P.Complete :=
    generatedPref_complete c hFrom hFN

  have hTrans : P.Transitive :=
    generatedPref_transitive c hFrom hFN hCC

  rcases Preference.exists_utility_of_encodable_complete_transitive P hComp hTrans with
    ⟨u, hRep⟩

  refine ⟨u, ?_⟩
  intro A hAFin
  have hA : c.choose A = (generatedChoiceFromGeneratedPref c).choose A :=
    choose_eq_generatedChoiceFromGeneratedPref_of_finite c hFrom hFN hCC hAFin
  have hChoice : P.generatedChoice = Utility.generatedChoice u :=
    Preference.generatedChoice_eq_generatedChoice_of_represents hRep
  calc
    c.choose A = (generatedChoiceFromGeneratedPref c).choose A := hA
    _ = P.generatedChoice.choose A := rfl
    _ = (Utility.generatedChoice u).choose A := by simp [hChoice]

/-!
### Chapter 1 summary theorems for choice
-/

/--
Finite-domain summary theorem for choice:
a choice function is utility-rationalisable if and only if it chooses from
feasible sets, satisfies finite nonemptiness, and is choice coherent.
-/
theorem exists_rationalizes_iff_axioms_finite
    [Fintype α]
    (c : ChoiceFunction α) :
    (∃ u : Utility.UtilityFunction α, Utility.Rationalizes u c) ↔
      c.ChoosesFrom ∧ c.FiniteNonempty ∧ c.ChoiceCoherent := by
  constructor
  · rintro ⟨u, hRat⟩
    exact ⟨Utility.choosesFrom_of_rationalizes hRat,
      Utility.finiteNonempty_of_rationalizes hRat,
      Utility.choiceCoherent_of_rationalizes hRat⟩
  · rintro ⟨hFrom, hFN, hCC⟩
    exact exists_utility_rationalizing_choice c hFrom hFN hCC

/--
Encodable-domain existence theorem for choice on finite menus.
-/
theorem exists_rationalizesOnFinite_of_axioms_encodable
    [Encodable α]
    (c : ChoiceFunction α)
    (hFrom : c.ChoosesFrom)
    (hFN : c.FiniteNonempty)
    (hCC : c.ChoiceCoherent) :
    ∃ u : Utility.UtilityFunction α, Utility.RationalizesOnFinite u c := by
  exact exists_utility_rationalizing_choice_on_finite_sets c hFrom hFN hCC

end ChoiceFunction


end EcoLean
