import EcoLean.ChoicePreferenceUtility.OnSet

/-!
# Basic microeconomic language

This file introduces model-independent definitions used by the welfare theorem
translation: allocations, Pareto dominance, budget sets, and utility
maximizers.

The definitions are intentionally small and carrier-relative.  More structured
economies, such as pure exchange and private ownership economies, should build
on this layer rather than duplicating it.
-/

universe u v

namespace EcoLean
namespace Microeconomics

/-- An allocation assigns a bundle to each agent. -/
abbrev Allocation (Agent : Type u) (Bundle : Type v) : Type (max u v) :=
  Agent → Bundle

namespace Allocation

variable {Agent : Type u} {Bundle : Type v}

@[simp] theorem apply_mk (X : Allocation Agent Bundle) (i : Agent) :
    X i = X i :=
  rfl

end Allocation

/-! ## Utility maximizers and budget sets -/

/--
The set of maximizers of `u` over `S`.

This is definitionally the same set as the choice set generated by utility
maximization, but the standalone name is convenient in economic statements.
-/
def Maximizers {α : Type u} (u : α → ℝ) (S : Set α) : Set α :=
  (Utility.generatedChoice u).choose S

@[simp] theorem mem_maximizers_iff {α : Type u}
    {u : α → ℝ} {S : Set α} {x : α} :
    x ∈ Maximizers u S ↔ x ∈ S ∧ ∀ y : α, y ∈ S → u x ≥ u y := by
  rfl

theorem mem_of_mem_maximizers {α : Type u}
    {u : α → ℝ} {S : Set α} {x : α}
    (hx : x ∈ Maximizers u S) :
    x ∈ S :=
  hx.1

theorem utility_ge_of_mem_maximizers {α : Type u}
    {u : α → ℝ} {S : Set α} {x y : α}
    (hx : x ∈ Maximizers u S) (hy : y ∈ S) :
    u x ≥ u y :=
  hx.2 y hy

theorem not_exists_gt_of_mem_maximizers {α : Type u}
    {u : α → ℝ} {S : Set α} {x : α}
    (hx : x ∈ Maximizers u S) :
    ¬ ∃ y : α, y ∈ S ∧ u y > u x := by
  intro h
  rcases h with ⟨y, hyS, hyx⟩
  exact not_lt_of_ge (utility_ge_of_mem_maximizers hx hyS) hyx

theorem mem_maximizers_of_mem_of_forall_ge {α : Type u}
    {u : α → ℝ} {S : Set α} {x : α}
    (hxS : x ∈ S) (hmax : ∀ y : α, y ∈ S → u x ≥ u y) :
    x ∈ Maximizers u S :=
  ⟨hxS, hmax⟩

/--
The budget set induced by a value function, a feasible set, and wealth.

For a price vector `p`, the value function will typically be `fun x => ⟪p, x⟫`.
-/
def BudgetSet {α : Type u} (value : α → ℝ) (S : Set α) (wealth : ℝ) : Set α :=
  {x : α | x ∈ S ∧ value x ≤ wealth}

@[simp] theorem mem_budgetSet_iff {α : Type u}
    {value : α → ℝ} {S : Set α} {wealth : ℝ} {x : α} :
    x ∈ BudgetSet value S wealth ↔ x ∈ S ∧ value x ≤ wealth :=
  Iff.rfl

theorem budgetSet_subset {α : Type u}
    {value : α → ℝ} {S : Set α} {wealth : ℝ} :
    BudgetSet value S wealth ⊆ S := by
  intro x hx
  exact hx.1

theorem value_le_of_mem_budgetSet {α : Type u}
    {value : α → ℝ} {S : Set α} {wealth : ℝ} {x : α}
    (hx : x ∈ BudgetSet value S wealth) :
    value x ≤ wealth :=
  hx.2

theorem mem_budgetSet_of_mem_of_value_le {α : Type u}
    {value : α → ℝ} {S : Set α} {wealth : ℝ} {x : α}
    (hxS : x ∈ S) (hx : value x ≤ wealth) :
    x ∈ BudgetSet value S wealth :=
  ⟨hxS, hx⟩

theorem budgetSet_mono_wealth {α : Type u}
    {value : α → ℝ} {S : Set α} {w₁ w₂ : ℝ}
    (hw : w₁ ≤ w₂) :
    BudgetSet value S w₁ ⊆ BudgetSet value S w₂ := by
  intro x hx
  exact ⟨hx.1, le_trans hx.2 hw⟩

/--
If `x` maximizes utility on its budget set and spends exactly its wealth, then
any strictly better feasible alternative must be strictly more expensive.
-/
theorem strict_value_support_of_mem_maximizers {α : Type u}
    {u value : α → ℝ} {S : Set α} {wealth : ℝ} {x y : α}
    (hx : x ∈ Maximizers u (BudgetSet value S wealth))
    (hxw : value x = wealth)
    (hyS : y ∈ S)
    (hyu : u y > u x) :
    value y > value x := by
  by_contra hnot
  have hy_le_x : value y ≤ value x := le_of_not_gt hnot
  have hyBudget : y ∈ BudgetSet value S wealth := by
    exact ⟨hyS, by simpa [hxw] using hy_le_x⟩
  exact not_exists_gt_of_mem_maximizers hx ⟨y, hyBudget, hyu⟩

/--
Weak price support from budget maximization plus a local-improvement principle.

The final premise is the abstract place where local non-satiation and the
geometry of prices will be discharged in concrete commodity spaces.
-/
theorem weak_value_support_of_mem_maximizers_of_local_improvement
    {α : Type u}
    {u value : α → ℝ} {S : Set α} {wealth : ℝ} {x y : α}
    (hx : x ∈ Maximizers u (BudgetSet value S wealth))
    (hxw : value x = wealth)
    (hImprove :
      ∀ z : α, z ∈ S → value z < wealth → u z ≥ u x →
        ∃ z' : α, z' ∈ S ∧ value z' ≤ wealth ∧ u z' > u x)
    (hyS : y ∈ S)
    (hyu : u y ≥ u x) :
    value y ≥ value x := by
  by_contra hnot
  have hy_lt_x : value y < value x := lt_of_not_ge hnot
  have hy_lt_wealth : value y < wealth := by
    simpa [hxw] using hy_lt_x
  rcases hImprove y hyS hy_lt_wealth hyu with ⟨z, hzS, hzBudget, hzu⟩
  exact not_exists_gt_of_mem_maximizers hx ⟨z, ⟨hzS, hzBudget⟩, hzu⟩

/-! ## Pareto dominance and efficiency -/

/--
`X` Pareto-dominates `Y` for a set of agents if all listed agents weakly prefer
their bundle in `X`, and some listed agent strictly prefers it, as measured by
the utility profile `U`.
-/
def ParetoDominates {Agent : Type u} {Bundle : Type v}
    (agents : Set Agent) (U : Agent → Bundle → ℝ)
    (X Y : Allocation Agent Bundle) : Prop :=
  (∀ i : Agent, i ∈ agents → U i (X i) ≥ U i (Y i)) ∧
    ∃ i : Agent, i ∈ agents ∧ U i (X i) > U i (Y i)

theorem paretoDominates_weak {Agent : Type u} {Bundle : Type v}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X Y : Allocation Agent Bundle}
    (h : ParetoDominates agents U X Y) :
    ∀ i : Agent, i ∈ agents → U i (X i) ≥ U i (Y i) :=
  h.1

theorem paretoDominates_strict_witness {Agent : Type u} {Bundle : Type v}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X Y : Allocation Agent Bundle}
    (h : ParetoDominates agents U X Y) :
    ∃ i : Agent, i ∈ agents ∧ U i (X i) > U i (Y i) :=
  h.2

theorem paretoDominates_trans {Agent : Type u} {Bundle : Type v}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X Y Z : Allocation Agent Bundle}
    (hXY : ParetoDominates agents U X Y)
    (hYZ : ParetoDominates agents U Y Z) :
    ParetoDominates agents U X Z := by
  constructor
  · intro i hi
    exact le_trans (hYZ.1 i hi) (hXY.1 i hi)
  · rcases hXY.2 with ⟨i, hi, hlt⟩
    exact ⟨i, hi, lt_of_le_of_lt (hYZ.1 i hi) hlt⟩

theorem not_paretoDominates_self {Agent : Type u} {Bundle : Type v}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    (X : Allocation Agent Bundle) :
    ¬ ParetoDominates agents U X X := by
  intro h
  rcases h.2 with ⟨i, _hi, hlt⟩
  exact lt_irrefl (U i (X i)) hlt

theorem paretoDominates_asymm {Agent : Type u} {Bundle : Type v}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X Y : Allocation Agent Bundle}
    (hXY : ParetoDominates agents U X Y) :
    ¬ ParetoDominates agents U Y X := by
  intro hYX
  exact not_paretoDominates_self X (paretoDominates_trans hXY hYX)

/--
Pareto efficiency relative to an arbitrary feasible-allocation set.

The first conjunct records feasibility of `X`; the second says no feasible
allocation Pareto-dominates it.
-/
def ParetoEfficient {Agent : Type u} {Bundle : Type v}
    (feasible : Set (Allocation Agent Bundle))
    (agents : Set Agent) (U : Agent → Bundle → ℝ)
    (X : Allocation Agent Bundle) : Prop :=
  X ∈ feasible ∧
    ¬ ∃ Y : Allocation Agent Bundle, Y ∈ feasible ∧ ParetoDominates agents U Y X

theorem feasible_of_paretoEfficient {Agent : Type u} {Bundle : Type v}
    {feasible : Set (Allocation Agent Bundle)}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X : Allocation Agent Bundle}
    (h : ParetoEfficient feasible agents U X) :
    X ∈ feasible :=
  h.1

theorem not_exists_paretoDominates_of_paretoEfficient
    {Agent : Type u} {Bundle : Type v}
    {feasible : Set (Allocation Agent Bundle)}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X : Allocation Agent Bundle}
    (h : ParetoEfficient feasible agents U X) :
    ¬ ∃ Y : Allocation Agent Bundle, Y ∈ feasible ∧ ParetoDominates agents U Y X :=
  h.2

theorem paretoEfficient_intro {Agent : Type u} {Bundle : Type v}
    {feasible : Set (Allocation Agent Bundle)}
    {agents : Set Agent} {U : Agent → Bundle → ℝ}
    {X : Allocation Agent Bundle}
    (hX : X ∈ feasible)
    (hNoDom :
      ¬ ∃ Y : Allocation Agent Bundle, Y ∈ feasible ∧ ParetoDominates agents U Y X) :
    ParetoEfficient feasible agents U X :=
  ⟨hX, hNoDom⟩

end Microeconomics
end EcoLean
