import EcoLean.GameTheory.StaticGames.SelfConfirmingEquilibrium
import EcoLean.GameTheory.StaticGames.MixedStrategies

/-!
# Anonymous self-confirming equilibrium

Following Battigalli–Catonini–De Vito §6.3.2. In *anonymous* (recurrent, population) interaction a
role `i` is filled by agents drawn at random from a large population, and a mixed action `αᵢ ∈ Δ(Aᵢ)`
records the *fractions* of `i`-agents playing each pure action. Different agents may hold different
conjectures, so each pure action `aᵢ ∈ supp αᵢ` carries its own conjecture `μ_{i,aᵢ}` over the
opponents' play. A profile is an **anonymous self-confirming equilibrium** (Definition 27) when, for
every role `i` and action `aᵢ` actually played:

* (rationality) `aᵢ` is a best response to `μ_{i,aᵢ}`, and
* (confirmed conjectures) the distribution over feedback messages that `μ_{i,aᵢ}` predicts (with `i`
  playing `aᵢ`) coincides with the one generated by the actual population play `α`.

* `messageProb` — the probability of a feedback message under a conjecture (or under the population
  play) when `i` plays `aᵢ`.
* `IsAnonymousSelfConfirmingEquilibrium` (Definition 27).
* `pure_isAnonymousSelfConfirmingEquilibriumProfile` (Remark 19): every pure self-confirming
  equilibrium is a degenerate anonymous one (all agents of a population play the same action).
-/

namespace EcoLean.GameTheory

namespace StaticGame

open scoped BigOperators
open Classical

variable {G : StaticGame} [Fintype G.Player] [DecidableEq G.Player] [∀ i, Fintype (G.Action i)]
  {M : G.Player → Type*}

/-- The **independent population distribution** induced by a mixed profile `α`: the probability of an
action profile `b` when each role's action is drawn independently from `α`. -/
noncomputable def mixedProfileDist (α : G.MixedProfile) : G.ActionProfile → ℝ :=
  fun b => ∏ j, α j (b j)

/-- The Dirac population (everyone plays `a` for sure) is the point mass at `a`. -/
theorem mixedProfileDist_single {a : G.ActionProfile} :
    G.mixedProfileDist (fun i => Pi.single (a i) 1) = G.dirac a := by
  funext b
  unfold mixedProfileDist dirac
  by_cases hba : b = a
  · rw [if_pos hba]
    refine Finset.prod_eq_one fun j _ => ?_
    rw [hba]; exact Pi.single_eq_same (a j) 1
  · rw [if_neg hba]
    obtain ⟨j₀, hj₀⟩ := Function.ne_iff.mp hba
    exact Finset.prod_eq_zero (Finset.mem_univ j₀) (Pi.single_eq_of_ne hj₀ 1)

/-- The probability that role `i`, playing `aᵢ`, receives feedback message `m`, under the conjecture
`μ` over opponents' play: the `μ`-mass of profiles whose feedback (with `i` deviating to `aᵢ`) is
`m`. -/
noncomputable def messageProb (f : ∀ i, G.ActionProfile → M i)
    (i : G.Player) (aᵢ : G.Action i) (μ : G.ActionProfile → ℝ) (m : M i) : ℝ :=
  ∑ b : G.ActionProfile, if f i (G.deviate b i aᵢ) = m then μ b else 0

/-- `(α, μ)` is an **anonymous self-confirming equilibrium** of the game with feedback `f`
(Definition 27): `α` is a population profile, and for every role `i` and action `aᵢ` played with
positive frequency, the conjecture `μ i aᵢ` is a confirmed best response — `aᵢ` maximises the
expected payoff under `μ i aᵢ`, and `μ i aᵢ` reproduces the true feedback-message distribution. -/
def IsAnonymousSelfConfirmingEquilibrium (f : ∀ i, G.ActionProfile → M i)
    (α : G.MixedProfile) (μ : ∀ i, G.Action i → G.ActionProfile → ℝ) : Prop :=
  (∀ i, α i ∈ stdSimplex ℝ (G.Action i)) ∧
    ∀ (i : G.Player) (aᵢ : G.Action i), α i aᵢ ≠ 0 →
      G.IsCorrelatedDistribution (μ i aᵢ) ∧ G.IsBestResponseToBelief (μ i aᵢ) i aᵢ ∧
        ∀ m : M i, G.messageProb f i aᵢ (μ i aᵢ) m = G.messageProb f i aᵢ (G.mixedProfileDist α) m

/-- `α` is an **anonymous self-confirming equilibrium population profile** if some profile of
confirmed conjectures supports it. -/
def IsAnonymousSelfConfirmingEquilibriumProfile (f : ∀ i, G.ActionProfile → M i)
    (α : G.MixedProfile) : Prop :=
  ∃ μ : ∀ i, G.Action i → G.ActionProfile → ℝ, G.IsAnonymousSelfConfirmingEquilibrium f α μ

variable {f : ∀ i, G.ActionProfile → M i}

/-- **Remark 19.** Every pure self-confirming equilibrium is a degenerate anonymous self-confirming
equilibrium: take each population to play its equilibrium action with probability one. The single
conjecture transfers; confirmation holds because the actual play is the equilibrium profile, so the
confirmed pure conjecture already reproduces the (degenerate) message distribution `[f a = m]`. -/
theorem pure_isAnonymousSelfConfirmingEquilibriumProfile {a : G.ActionProfile}
    (h : G.IsSelfConfirmingEquilibriumActionProfile f a) :
    G.IsAnonymousSelfConfirmingEquilibriumProfile f (fun i => Pi.single (a i) 1) := by
  obtain ⟨ν, hν⟩ := h
  refine ⟨fun i _ => ν i, fun i => single_mem_stdSimplex ℝ (a i), fun i aᵢ haᵢ => ?_⟩
  have haeq : aᵢ = a i := by
    by_contra hne
    exact haᵢ (Pi.single_eq_of_ne hne 1)
  subst haeq
  obtain ⟨hdist, hbest, hconf⟩ := hν i
  refine ⟨hdist, hbest, fun m => ?_⟩
  have hlhs : G.messageProb f i (a i) (ν i) m = if f i a = m then 1 else 0 := by
    unfold messageProb
    have h1 : ∀ b, (if f i (G.deviate b i (a i)) = m then ν i b else 0)
        = (if f i a = m then ν i b else 0) := by
      intro b
      by_cases hb : 0 < ν i b
      · rw [hconf b hb]
      · have hb0 : ν i b = 0 := le_antisymm (not_lt.mp hb) (hdist.1 b)
        simp [hb0]
    rw [Finset.sum_congr rfl (fun b _ => h1 b)]
    by_cases hc : f i a = m
    · simp only [if_pos hc]; exact hdist.2
    · simp only [if_neg hc, Finset.sum_const_zero]
  have hrhs : G.messageProb f i (a i) (G.mixedProfileDist (fun i => Pi.single (a i) 1)) m
      = if f i a = m then 1 else 0 := by
    rw [mixedProfileDist_single]
    unfold messageProb
    rw [show (∑ b, if f i (G.deviate b i (a i)) = m then G.dirac a b else 0)
        = ∑ b, G.dirac a b * (if f i (G.deviate b i (a i)) = m then 1 else 0) from
      Finset.sum_congr rfl fun b _ => by split_ifs <;> simp]
    rw [sum_dirac_mul, G.deviate_eq_self]
  rw [hlhs, hrhs]

/-! ### Remark 18: every mixed Nash equilibrium is an anonymous self-confirming equilibrium -/

/-- The independent population distribution of a profile of mixed strategies is a probability
distribution over action profiles (a product of distributions, summing to one). -/
theorem mixedProfileDist_isCorrelatedDistribution {α : G.MixedProfile}
    (hα : ∀ j, α j ∈ stdSimplex ℝ (G.Action j)) :
    G.IsCorrelatedDistribution (G.mixedProfileDist α) := by
  refine ⟨fun b => Finset.prod_nonneg fun j _ => (hα j).1 (b j), ?_⟩
  unfold mixedProfileDist
  rw [← Fintype.piFinset_univ, ← Finset.prod_univ_sum]
  exact Finset.prod_eq_one fun j _ => (hα j).2

/-- The fiber of `· ↦ update · i x` over `c` (the profiles deviating to `c`) carries total `α`-mass
`(∑ αᵢ) · ∏_{j≠i} αⱼ(cⱼ)` when `cᵢ = x`, and is empty otherwise. -/
theorem fiber_prod_sum (i : G.Player) (x : G.Action i) (c : G.ActionProfile) (α : G.MixedProfile) :
    ∑ b ∈ Finset.univ.filter (fun b : G.ActionProfile => Function.update b i x = c),
        (∏ j, α j (b j))
      = if c i = x then (∑ v, α i v) * ∏ j ∈ Finset.univ \ {i}, α j (c j) else 0 := by
  by_cases hci : c i = x
  · rw [if_pos hci]
    have hfilter : (Finset.univ.filter fun b : G.ActionProfile => Function.update b i x = c)
        = Finset.univ.image (fun v : G.Action i => Function.update c i v) := by
      ext b
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_image]
      constructor
      · intro hb
        refine ⟨b i, ?_⟩
        funext j
        by_cases hj : j = i
        · rw [hj, Function.update_self]
        · rw [Function.update_of_ne hj, ← hb, Function.update_of_ne hj]
      · rintro ⟨v, rfl⟩
        funext j
        by_cases hj : j = i
        · rw [hj, Function.update_self, hci]
        · rw [Function.update_of_ne hj, Function.update_of_ne hj]
    rw [hfilter, Finset.sum_image (fun v _ w _ hvw => by
      have := congrFun hvw i; rwa [Function.update_self, Function.update_self] at this)]
    have hprodv : ∀ v : G.Action i, (∏ j, α j (Function.update c i v j))
        = α i v * ∏ j ∈ Finset.univ \ {i}, α j (c j) := by
      intro v
      rw [Finset.prod_eq_mul_prod_diff_singleton_of_mem (Finset.mem_univ i)
        (fun j => α j (Function.update c i v j)), Function.update_self]
      congr 1
      refine Finset.prod_congr rfl fun j hj => ?_
      rw [Function.update_of_ne (by simpa using (Finset.mem_sdiff.mp hj).2)]
    rw [Finset.sum_congr rfl (fun v _ => hprodv v), ← Finset.sum_mul]
  · rw [if_neg hci, show (Finset.univ.filter
      fun b : G.ActionProfile => Function.update b i x = c) = ∅ from
      Finset.filter_eq_empty_iff.mpr fun b _ hb => hci (by rw [← hb, Function.update_self]),
      Finset.sum_empty]

/-- **The marginalization bridge.** Summing the independent population distribution against `i`'s
deterministic deviation to `x` marginalises out `i`'s own (probability-one) randomisation, leaving
the pure-deviation payoff `purePayoffAgainst i x α`. -/
theorem sum_mixedProfileDist_devPayoff_eq_purePayoff (i : G.Player) (x : G.Action i)
    (α : G.MixedProfile) (hαi : ∑ v, α i v = 1) :
    ∑ b : G.ActionProfile, G.mixedProfileDist α b * G.devPayoff b i x
      = G.purePayoffAgainst i x α := by
  rw [purePayoffAgainst, mixedPayoff_update]
  unfold mixedProfileDist
  rw [← Finset.sum_fiberwise_of_maps_to (t := Finset.univ)
    (g := fun b : G.ActionProfile => Function.update b i x)
    (f := fun b => (∏ j, α j (b j)) * G.devPayoff b i x)
    (fun b _ => Finset.mem_univ (Function.update b i x))]
  refine Finset.sum_congr rfl fun c _ => ?_
  have hdev : ∀ b ∈ Finset.univ.filter (fun b => Function.update b i x = c),
      (∏ j, α j (b j)) * G.devPayoff b i x = (∏ j, α j (b j)) * G.payoff i c := by
    intro b hb
    rw [Finset.mem_filter] at hb
    congr 1
    show G.payoff i (G.deviate b i x) = G.payoff i c
    congr 1
    exact hb.2
  rw [Finset.sum_congr rfl hdev, ← Finset.sum_mul, fiber_prod_sum]
  by_cases hci : c i = x
  · rw [if_pos hci, hαi, one_mul, hci, Pi.single_eq_same, one_mul]
  · rw [if_neg hci, zero_mul, Pi.single_eq_of_ne hci 1, zero_mul, zero_mul]

/-- **Remark 18.** Every mixed Nash equilibrium is an anonymous self-confirming equilibrium population
profile, for any feedback: take each agent's conjecture to be the true independent population
distribution. Confirmation is then immediate (the conjecture *is* the true distribution), and
rationality is the equalizing principle — every action played with positive frequency is a pure best
response to the population play. -/
theorem mixedNash_isAnonymousSelfConfirmingEquilibriumProfile {α : G.MixedProfile}
    (hα : G.IsMixedNashEquilibrium α) :
    G.IsAnonymousSelfConfirmingEquilibriumProfile f α := by
  refine ⟨fun _ _ => G.mixedProfileDist α, hα.1, fun i aᵢ haᵢ => ?_⟩
  refine ⟨mixedProfileDist_isCorrelatedDistribution hα.1, fun ci => ?_, fun _ => rfl⟩
  rw [sum_mixedProfileDist_devPayoff_eq_purePayoff i ci α (hα.1 i).2,
    sum_mixedProfileDist_devPayoff_eq_purePayoff i aᵢ α (hα.1 i).2]
  exact purePayoffAgainst_le_of_mem_support G hα i haᵢ ci

end StaticGame

end EcoLean.GameTheory
