import EcoLean.ChoicePreferenceUtility.OnSet
import EcoLean.GameTheory.MathLanguage.ProbabilityMeasures
import Mathlib.Probability.ProbabilityMassFunction.Constructions
import Mathlib.Probability.ProbabilityMassFunction.Monad
import Mathlib.Topology.Algebra.InfiniteSum.Ring
import Mathlib.Tactic

/-!
# Lotteries and vNM-style preference axioms

This file starts the expected-utility side of the game-theory foundations.
Lotteries are represented by mathlib probability mass functions.  The
definitions are intentionally thin wrappers around the existing
`EcoLean.Preference` API: the primitive object is still a weak preference
relation, now specialized to lotteries and restricted to a carrier set when
needed.

The continuity axiom below is the Archimedean/mixture continuity axiom used in
von Neumann-Morgenstern expected utility theory.  It is not a Debreu-style
topological continuity theorem for preferences over commodity spaces.
-/

universe u

namespace EcoLean
namespace GameTheory
namespace ExpectedUtility

variable {Outcome : Type u}

/-! ## Lotteries and mixtures -/

/-- A lottery over outcomes, represented as a probability mass function. -/
abbrev Lottery (Outcome : Type u) := PMF Outcome

/-- The set of lotteries whose support is contained in a carrier of outcomes. -/
def LotteriesOn (S : Set Outcome) : Set (Lottery Outcome) :=
  {p | p.support ⊆ S}

/-- The degenerate lottery putting probability one on `x`. -/
noncomputable def degenerate (x : Outcome) : Lottery Outcome :=
  PMF.pure x

/--
The mixture lottery that plays `p` with probability `a` and `q` with the
remaining probability.
-/
noncomputable def mix (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    Lottery Outcome :=
  (PMF.bernoulli a ha).bind fun b => if b then p else q

/-- The real-valued probability assigned by a lottery to an outcome. -/
noncomputable def prob (p : Lottery Outcome) (x : Outcome) : ℝ :=
  (p x).toReal

/-- The finite expected value of an outcome utility index under a lottery. -/
noncomputable def expectedValue [Fintype Outcome]
    (u : Outcome → ℝ) (p : Lottery Outcome) : ℝ :=
  ∑ x : Outcome, prob p x * u x

/-- A carrier of lotteries is closed under binary probabilistic mixtures. -/
def MixtureClosed (S : Set (Lottery Outcome)) : Prop :=
  ∀ ⦃p q : Lottery Outcome⦄, p ∈ S → q ∈ S →
    ∀ (a : NNReal) (ha : a ≤ 1), mix p q a ha ∈ S

/--
The smallest syntactic class of lotteries generated by degenerate lotteries
over an outcome carrier and closed under binary mixtures.

Parsert/Kaliszyk use an induction principle of this shape for finite-support
PMFs.  Keeping it explicit gives the forward vNM proof a stable Lean target
while we connect it to broader PMF decomposition results.
-/
inductive MixtureGenerated (C : Set Outcome) : Lottery Outcome → Prop where
  | ofOutcome {x : Outcome} (hx : x ∈ C) :
      MixtureGenerated C (degenerate x)
  | mix {p q : Lottery Outcome}
      (hp : MixtureGenerated C p) (hq : MixtureGenerated C q)
      (a : NNReal) (ha : a ≤ 1) :
      MixtureGenerated C (mix p q a ha)

/-- The carrier of lotteries generated from outcomes in `C` by binary mixtures. -/
def GeneratedLotteries (C : Set Outcome) : Set (Lottery Outcome) :=
  {p | MixtureGenerated C p}

/-- The finite support of a lottery as a `Finset`, when outcomes are finite. -/
noncomputable def supportFinset [Fintype Outcome] (p : Lottery Outcome) :
    Finset Outcome :=
  Finset.univ.filter fun x => p x ≠ 0

@[simp] theorem mem_supportFinset [Fintype Outcome]
    {p : Lottery Outcome} {x : Outcome} :
    x ∈ supportFinset p ↔ x ∈ p.support := by
  simp [supportFinset, PMF.mem_support_iff]

theorem degenerate_mem_generatedLotteries
    {C : Set Outcome} {x : Outcome}
    (hx : x ∈ C) :
    degenerate x ∈ GeneratedLotteries C :=
  MixtureGenerated.ofOutcome hx

theorem generatedLotteries_mixtureClosed (C : Set Outcome) :
    MixtureClosed (GeneratedLotteries C) := by
  intro p q hp hq a ha
  exact MixtureGenerated.mix hp hq a ha

@[simp] theorem mem_lotteriesOn_iff {S : Set Outcome} {p : Lottery Outcome} :
    p ∈ LotteriesOn S ↔ p.support ⊆ S :=
  Iff.rfl

theorem lotteriesOn_mono {S T : Set Outcome}
    (hST : S ⊆ T) :
    LotteriesOn S ⊆ LotteriesOn T := by
  intro p hp x hx
  exact hST (hp hx)

theorem degenerate_mem_lotteriesOn {S : Set Outcome} {x : Outcome}
    (hx : x ∈ S) :
    degenerate x ∈ LotteriesOn S := by
  intro y hy
  have hyx : y = x := (PMF.mem_support_pure_iff x y).mp hy
  simpa [hyx] using hx

theorem mix_mem_lotteriesOn {S : Set Outcome} {p q : Lottery Outcome}
    (hp : p ∈ LotteriesOn S) (hq : q ∈ LotteriesOn S)
    (a : NNReal) (ha : a ≤ 1) :
    mix p q a ha ∈ LotteriesOn S := by
  intro x hx
  rw [mix] at hx
  rcases (PMF.mem_support_bind_iff (p := PMF.bernoulli a ha)
      (f := fun b => if b then p else q) x).mp hx with ⟨b, _hb, hxb⟩
  cases b <;> simp at hxb
  · exact hq hxb
  · exact hp hxb

theorem lotteriesOn_mixtureClosed (S : Set Outcome) :
    MixtureClosed (LotteriesOn S) := by
  intro p q hp hq a ha
  exact mix_mem_lotteriesOn hp hq a ha

theorem MixtureGenerated.mem_lotteriesOn
    {C : Set Outcome} {p : Lottery Outcome}
    (hp : MixtureGenerated C p) :
    p ∈ LotteriesOn C := by
  induction hp with
  | ofOutcome hx =>
      exact degenerate_mem_lotteriesOn hx
  | mix hp hq a ha ihp ihq =>
      exact mix_mem_lotteriesOn ihp ihq a ha

theorem generatedLotteries_subset_lotteriesOn (C : Set Outcome) :
    GeneratedLotteries C ⊆ LotteriesOn C := by
  intro p hp
  exact hp.mem_lotteriesOn

theorem MixtureGenerated.mem_of_degenerate_mem_of_mixtureClosed
    {C : Set Outcome} {S : Set (Lottery Outcome)} {p : Lottery Outcome}
    (hp : MixtureGenerated C p)
    (hDegenerate : ∀ x : Outcome, x ∈ C → degenerate x ∈ S)
    (hS : MixtureClosed S) :
    p ∈ S := by
  induction hp with
  | ofOutcome hx =>
      exact hDegenerate _ hx
  | mix hp hq a ha ihp ihq =>
      exact hS ihp ihq a ha

theorem mix_apply
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) (x : Outcome) :
    mix p q a ha x =
      (a : ENNReal) * p x + ((1 - a : NNReal) : ENNReal) * q x := by
  rw [mix, PMF.bind_apply]
  rw [tsum_fintype]
  simp [PMF.bernoulli_apply]

@[simp] theorem mix_zero (p q : Lottery Outcome) :
    mix p q 0 (by norm_num) = q := by
  ext x
  rw [mix_apply]
  simp

@[simp] theorem mix_one (p q : Lottery Outcome) :
    mix p q 1 le_rfl = p := by
  ext x
  rw [mix_apply]
  simp

@[simp] theorem mix_self
    (p : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    mix p p a ha = p := by
  rw [mix]
  simp only [ite_self]
  exact PMF.bind_const (PMF.bernoulli a ha) p

/--
Swapping the two branches of a mixture replaces the weight by its complement.
This is the Lean analogue of the AFP lemma `pmf-inverse-switch-eqals`.
-/
theorem mix_comm
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    mix p q a ha = mix q p (1 - a) (by simp) := by
  ext x
  rw [mix_apply, mix_apply]
  have hsub : (1 - (1 - a) : NNReal) = a :=
    tsub_tsub_cancel_of_le ha
  rw [hsub]
  rw [add_comm]

/-- A complement-weight form of `mix_comm`. -/
theorem mix_compl
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    mix p q (1 - a) (by simp) = mix q p a ha := by
  have hsub : (1 - (1 - a) : NNReal) = a :=
    tsub_tsub_cancel_of_le ha
  rw [mix_comm p q (1 - a) (by simp)]
  simp [hsub]

/-- Mixing a best/worst mixture with the same second branch multiplies weights. -/
theorem mix_mix_right
    (p q : Lottery Outcome) (a b : NNReal) (ha : a ≤ 1) (hb : b ≤ 1) :
    mix (mix p q a ha) q b hb =
      mix p q (b * a) (by nlinarith [ha, hb, zero_le a, zero_le b]) := by
  ext x
  rw [mix_apply, mix_apply, mix_apply]
  have hba : b * a ≤ 1 := by
    nlinarith [ha, hb, zero_le a, zero_le b]
  have hcompNN : (1 - b * a : NNReal) = b * (1 - a) + (1 - b) := by
    ext
    simp only [NNReal.coe_sub, hba, ha, hb, NNReal.coe_mul,
      NNReal.coe_one, NNReal.coe_add]
    ring
  have hcomp : ((1 - b * a : NNReal) : ENNReal) =
      (b : ENNReal) * ((1 - a : NNReal) : ENNReal) +
        ((1 - b : NNReal) : ENNReal) := by
    exact_mod_cast hcompNN
  rw [hcomp]
  rw [ENNReal.coe_mul]
  ring_nf

/-- Mixing two mixtures with the same endpoints combines their endpoint weights affinely. -/
theorem mix_mix
    (p q : Lottery Outcome) (a b c : NNReal)
    (ha : a ≤ 1) (hb : b ≤ 1) (hc : c ≤ 1) :
    mix (mix p q a ha) (mix p q b hb) c hc =
      mix p q (c * a + (1 - c) * b)
        (by
          calc
            c * a + (1 - c) * b ≤ c * 1 + (1 - c) * 1 := by gcongr
            _ = c + (1 - c) := by ring
            _ = 1 := by exact add_tsub_cancel_of_le hc) := by
  ext x
  rw [mix_apply, mix_apply, mix_apply, mix_apply]
  have hw : c * a + (1 - c) * b ≤ 1 := by
    calc
      c * a + (1 - c) * b ≤ c * 1 + (1 - c) * 1 := by gcongr
      _ = c + (1 - c) := by ring
      _ = 1 := by exact add_tsub_cancel_of_le hc
  have hweight : ((c * a + (1 - c) * b : NNReal) : ENNReal) =
      (c : ENNReal) * (a : ENNReal) +
        ((1 - c : NNReal) : ENNReal) * (b : ENNReal) := by
    exact_mod_cast rfl
  have hcompNN : (1 - (c * a + (1 - c) * b) : NNReal) =
      c * (1 - a) + (1 - c) * (1 - b) := by
    ext
    simp only [NNReal.coe_sub, hw, ha, hb, hc, NNReal.coe_mul,
      NNReal.coe_one, NNReal.coe_add]
    ring
  have hcomp : ((1 - (c * a + (1 - c) * b) : NNReal) : ENNReal) =
      (c : ENNReal) * ((1 - a : NNReal) : ENNReal) +
        ((1 - c : NNReal) : ENNReal) *
          ((1 - b : NNReal) : ENNReal) := by
    exact_mod_cast hcompNN
  rw [hcomp, hweight]
  ring_nf

theorem support_mix_subset
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    (mix p q a ha).support ⊆ p.support ∪ q.support := by
  intro x hx
  rw [mix] at hx
  rcases (PMF.mem_support_bind_iff (p := PMF.bernoulli a ha)
      (f := fun b => if b then p else q) x).mp hx with ⟨b, _hb, hxb⟩
  cases b <;> simp at hxb
  · exact Or.inr hxb
  · exact Or.inl hxb

theorem prob_mix
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) (x : Outcome) :
    prob (mix p q a ha) x =
      (a : ℝ) * prob p x + ((1 - a : NNReal) : ℝ) * prob q x := by
  unfold prob
  have hsub : (1 - (a : ENNReal)).toReal = ((1 - a : NNReal) : ℝ) := by
    have h : ((1 - a : NNReal) : ENNReal) = 1 - (a : ENNReal) := by
      simp [ENNReal.coe_sub]
    rw [← h]
    exact ENNReal.coe_toReal (1 - a)
  rw [mix_apply]
  rw [ENNReal.toReal_add
    (ENNReal.mul_ne_top ENNReal.coe_ne_top (p.apply_ne_top x))
    (ENNReal.mul_ne_top ENNReal.coe_ne_top (q.apply_ne_top x))]
  rw [ENNReal.toReal_mul, ENNReal.toReal_mul]
  simp [hsub]

theorem expectedValue_mix [Fintype Outcome]
    (u : Outcome → ℝ)
    (p q : Lottery Outcome) (a : NNReal) (ha : a ≤ 1) :
    expectedValue u (mix p q a ha) =
      (a : ℝ) * expectedValue u p +
        ((1 - a : NNReal) : ℝ) * expectedValue u q := by
  unfold expectedValue
  simp_rw [prob_mix]
  calc
    (∑ x : Outcome,
        ((a : ℝ) * prob p x + ((1 - a : NNReal) : ℝ) * prob q x) * u x)
        =
          ∑ x : Outcome,
            ((a : ℝ) * (prob p x * u x) +
              ((1 - a : NNReal) : ℝ) * (prob q x * u x)) := by
            refine Finset.sum_congr rfl ?_
            intro x _hx
            ring
    _ =
        (a : ℝ) * (∑ x : Outcome, prob p x * u x) +
          ((1 - a : NNReal) : ℝ) * (∑ x : Outcome, prob q x * u x) := by
        rw [Finset.sum_add_distrib]
        rw [← Finset.mul_sum, ← Finset.mul_sum]

theorem expectedValue_degenerate [Fintype Outcome] [DecidableEq Outcome]
    (u : Outcome → ℝ) (x : Outcome) :
    expectedValue u (degenerate x) = u x := by
  unfold expectedValue prob degenerate
  rw [Finset.sum_eq_single x]
  · simp [PMF.pure_apply]
  · intro y _hy hne
    simp [PMF.pure_apply, hne]
  · intro hx
    exact False.elim (hx (Finset.mem_univ x))

/-- A finite PMF has nonempty support. -/
theorem supportFinset_nonempty [Fintype Outcome] (p : Lottery Outcome) :
    (supportFinset p).Nonempty := by
  classical
  by_contra h
  have hzero : ∀ x : Outcome, p x = 0 := by
    intro x
    have hx : x ∉ supportFinset p := by
      intro hx
      exact h ⟨x, hx⟩
    exact (PMF.apply_eq_zero_iff p x).mpr (by simpa using hx)
  have hsum_zero : (∑' x : Outcome, p x) = 0 := by
    simp [hzero]
  rw [PMF.tsum_coe] at hsum_zero
  norm_num at hsum_zero

/-- A lottery whose finite support is a singleton is the corresponding degenerate lottery. -/
theorem eq_degenerate_of_supportFinset_eq_singleton
    [Fintype Outcome] {p : Lottery Outcome} {x : Outcome}
    (h : supportFinset p = {x}) :
    p = degenerate x := by
  classical
  have hsupport : p.support = {x} := by
    ext y
    rw [← mem_supportFinset]
    simp [h]
  have hxone : p x = 1 := (PMF.apply_eq_one_iff p x).mpr hsupport
  ext y
  by_cases hy : y = x
  · subst y
    simp [degenerate, PMF.pure_apply, hxone]
  · have hynot : y ∉ p.support := by
      rw [hsupport]
      simp [hy]
    have hyzero : p y = 0 := (PMF.apply_eq_zero_iff p y).mpr hynot
    simp [degenerate, PMF.pure_apply, hy, hyzero]

/--
Every finite lottery is generated by repeated binary mixtures of degenerate
lotteries.  This is the PMF decomposition bridge needed to move from the
syntactic generated carrier to all finite-outcome lotteries.
-/
theorem mixtureGenerated_univ [Fintype Outcome]
    (p : Lottery Outcome) :
    MixtureGenerated (Set.univ : Set Outcome) p := by
  classical
  let C : Set Outcome := Set.univ
  change MixtureGenerated C p
  refine (measure (fun p : Lottery Outcome => (supportFinset p).card)).wf.induction
    (C := fun p => MixtureGenerated C p) p ?_
  intro p ih
  let supp := supportFinset p
  have hsupp_nonempty : supp.Nonempty := by
    simpa [supp] using supportFinset_nonempty p
  by_cases hcard_one : supp.card = 1
  · rcases Finset.card_eq_one.mp hcard_one with ⟨x, hx⟩
    have hpure : p = degenerate x :=
      eq_degenerate_of_supportFinset_eq_singleton (p := p) hx
    rw [hpure]
    exact MixtureGenerated.ofOutcome (Set.mem_univ x)
  · have hcard_pos : 0 < supp.card := Finset.card_pos.mpr hsupp_nonempty
    have hcard_gt_one : 1 < supp.card := by omega
    rcases hsupp_nonempty with ⟨x, hx⟩
    have hexists_other : ∃ y ∈ supp, y ≠ x := by
      by_contra hnone
      have hsub : supp ⊆ {x} := by
        intro y hy
        by_contra hyx
        have hyx' : y ≠ x := by simpa using hyx
        exact hnone ⟨y, hy, hyx'⟩
      have hcard_le : supp.card ≤ ({x} : Finset Outcome).card :=
        Finset.card_le_card hsub
      simp at hcard_le
      omega
    rcases hexists_other with ⟨y, hy, hyx⟩
    let tail : Set Outcome := {z | z ≠ x}
    have htail_nonempty : ∃ z ∈ tail, z ∈ p.support := by
      exact ⟨y, hyx, (mem_supportFinset.mp (by simpa [supp] using hy))⟩
    let q : Lottery Outcome := p.filter tail htail_nonempty
    have hq_smaller :
        (supportFinset q).card < (supportFinset p).card := by
      have hsub : supportFinset q ⊆ (supportFinset p).erase x := by
        intro z hz
        have hzsupport : z ∈ q.support := mem_supportFinset.mp hz
        have hztail_support : z ∈ tail ∧ z ∈ p.support := by
          simpa [q] using (PMF.mem_support_filter_iff (p := p)
            (s := tail) (h := htail_nonempty) (a := z)).mp hzsupport
        exact Finset.mem_erase.mpr
          ⟨hztail_support.1, mem_supportFinset.mpr hztail_support.2⟩
      exact lt_of_le_of_lt (Finset.card_le_card hsub)
        (Finset.card_erase_lt_of_mem (by simpa [supp] using hx))
    have hq_generated : MixtureGenerated C q := ih q hq_smaller
    let a : NNReal := (p x).toNNReal
    have hpx_ne_one : p x ≠ 1 := by
      intro hpx
      have hsupport : p.support = {x} := (PMF.apply_eq_one_iff p x).mp hpx
      have hsupp_singleton : supportFinset p = {x} := by
        ext z
        rw [mem_supportFinset]
        simp [hsupport]
      have : supp.card = 1 := by
        simp [supp, hsupp_singleton]
      exact hcard_one this
    have hpx_lt_one : p x < 1 :=
      lt_of_le_of_ne (PMF.coe_le_one p x) hpx_ne_one
    have ha_le : a ≤ 1 := by
      rw [← ENNReal.coe_le_coe]
      rw [ENNReal.coe_toNNReal (p.apply_ne_top x)]
      exact PMF.coe_le_one p x
    have ha_coe : (a : ENNReal) = p x :=
      ENNReal.coe_toNNReal (p.apply_ne_top x)
    have hcomp_coe : ((1 - a : NNReal) : ENNReal) = 1 - p x := by
      rw [ENNReal.coe_sub, ha_coe]
      norm_num
    have hcomp_nonzero : 1 - p x ≠ 0 := by
      rw [ne_eq, tsub_eq_zero_iff_le]
      exact not_le_of_gt hpx_lt_one
    have hcomp_ne_top : 1 - p x ≠ ⊤ :=
      ENNReal.sub_ne_top (by norm_num)
    have htail_mass : (∑' z : Outcome, tail.indicator (fun w => p w) z) = 1 - p x := by
      have hfinite :
          (∑' z : Outcome, tail.indicator (fun w => p w) z) =
            ∑ z : Outcome, tail.indicator (fun w => p w) z := by
        exact tsum_fintype _
      have hindicator_sum :
          (∑ z : Outcome, tail.indicator (fun w => p w) z) =
            ∑ z ∈ (Finset.univ.erase x), p z := by
        calc
          (∑ z : Outcome, tail.indicator (fun w => p w) z)
              = ∑ z : Outcome, if z ≠ x then p z else 0 := by
                refine Finset.sum_congr rfl ?_
                intro z _hz
                by_cases hz : z ≠ x <;> simp [tail, hz]
          _ = ∑ z ∈ (Finset.univ.filter fun z => z ≠ x), p z := by
                simpa using (Finset.sum_filter
                  (s := (Finset.univ : Finset Outcome))
                  (p := fun z => z ≠ x) (f := fun z => p z)).symm
          _ = ∑ z ∈ (Finset.univ.erase x), p z := by
                refine Finset.sum_congr ?_ ?_
                · ext z
                  simp
                · intro z _hz
                  rfl
      have hsum_all : (∑ z : Outcome, p z) = 1 := by
        simpa [tsum_fintype] using (PMF.tsum_coe p)
      have hsum_split : p x + ∑ z ∈ (Finset.univ.erase x), p z = 1 := by
        rw [Finset.add_sum_erase Finset.univ (fun z => p z) (Finset.mem_univ x)]
        exact hsum_all
      calc
        (∑' z : Outcome, tail.indicator (fun w => p w) z)
            = ∑ z : Outcome, tail.indicator (fun w => p w) z := hfinite
        _ = ∑ z ∈ (Finset.univ.erase x), p z := hindicator_sum
        _ = 1 - p x := by
          exact ENNReal.eq_sub_of_add_eq (p.apply_ne_top x) (by
            rw [add_comm]
            exact hsum_split)
    have htail_mass_fin :
        (∑ z : Outcome, tail.indicator (fun w => p w) z) = 1 - p x := by
      simpa [tsum_fintype] using htail_mass
    have hp_decomp : p = mix (degenerate x) q a ha_le := by
      ext z
      by_cases hz : z = x
      · subst z
        have hq_zero : q x = 0 := by
          exact PMF.filter_apply_eq_zero_of_notMem
            (p := p) (s := tail) (h := htail_nonempty) (by simp [tail])
        rw [mix_apply]
        simp [degenerate, PMF.pure_apply, q, hq_zero, ha_coe]
      · have hq_apply : q z = p z * (1 - p x)⁻¹ := by
          rw [PMF.filter_apply]
          simp [tail, hz]
          rw [htail_mass_fin]
        rw [mix_apply]
        have hpure_zero : degenerate x z = 0 := by
          simp [degenerate, PMF.pure_apply, hz]
        rw [hpure_zero, hcomp_coe, hq_apply]
        simp only [mul_zero, zero_add]
        symm
        rw [← mul_assoc, mul_comm (1 - p x) (p z), mul_assoc]
        rw [ENNReal.mul_inv_cancel hcomp_nonzero hcomp_ne_top]
        simp
    rw [hp_decomp]
    exact MixtureGenerated.mix
      (MixtureGenerated.ofOutcome (Set.mem_univ x)) hq_generated a ha_le

/-- On a finite nonempty outcome type, generated lotteries are all lotteries. -/
theorem generatedLotteries_univ [Fintype Outcome] :
    GeneratedLotteries (Set.univ : Set Outcome) = Set.univ := by
  ext p
  constructor
  · intro _hp
    exact Set.mem_univ p
  · intro _hp
    exact mixtureGenerated_univ p

/-! ## vNM preference axioms -/

/--
Independence: on a carrier of lotteries, mixing both sides with the same third
lottery preserves and reflects weak preference whenever the mixing weight is
strictly between zero and one.
-/
def VNMIndependent
    (P : Preference (Lottery Outcome))
    (S : Set (Lottery Outcome)) : Prop :=
  ∀ ⦃p q r : Lottery Outcome⦄,
    p ∈ S → q ∈ S → r ∈ S →
      ∀ (a : NNReal) (ha : a ≤ 1), 0 < a →
        (P.weakPref p q ↔ P.weakPref (mix p r a ha) (mix q r a ha))

theorem weakPref_mix_left_of_independent
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (hRat : P.RationalOn S)
    (hInd : VNMIndependent P S)
    {p q r : Lottery Outcome}
    (hp : p ∈ S) (hq : q ∈ S) (hr : r ∈ S)
    (hpq : P.weakPref p q)
    (a : NNReal) (ha : a ≤ 1) :
    P.weakPref (mix p r a ha) (mix q r a ha) := by
  by_cases hzero : a = 0
  · subst a
    simpa using (P.reflexiveOn_of_completeOn hRat.1) hr
  · have hpos : 0 < a := lt_of_le_of_ne bot_le (Ne.symm hzero)
    exact (hInd hp hq hr a ha hpos).mp hpq

theorem weakPref_mix_right_of_independent
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (hRat : P.RationalOn S)
    (hInd : VNMIndependent P S)
    {p q r : Lottery Outcome}
    (hp : p ∈ S) (hq : q ∈ S) (hr : r ∈ S)
    (hpq : P.weakPref p q)
    (a : NNReal) (ha : a ≤ 1) :
    P.weakPref (mix r p a ha) (mix r q a ha) := by
  by_cases hone : a = 1
  · subst a
    simpa using (P.reflexiveOn_of_completeOn hRat.1) hr
  · have hlt : a < 1 := lt_of_le_of_ne ha hone
    have hcomp_pos : 0 < (1 - a : NNReal) := tsub_pos_iff_lt.mpr hlt
    have hcomp_le : (1 - a : NNReal) ≤ 1 := by simp
    have h :=
      (hInd hp hq hr (1 - a) hcomp_le hcomp_pos).mp hpq
    simpa [mix_compl p r a ha, mix_compl q r a ha] using h

theorem weakPref_mix_right_iff_of_independent
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (hInd : VNMIndependent P S)
    {p q r : Lottery Outcome}
    (hp : p ∈ S) (hq : q ∈ S) (hr : r ∈ S)
    (a : NNReal) (ha : a ≤ 1) (hlt : a < 1) :
    (P.weakPref p q ↔ P.weakPref (mix r p a ha) (mix r q a ha)) := by
  have hcomp_pos : 0 < (1 - a : NNReal) := tsub_pos_iff_lt.mpr hlt
  have hcomp_le : (1 - a : NNReal) ≤ 1 := by simp
  have hiff := hInd hp hq hr (1 - a) hcomp_le hcomp_pos
  simpa [mix_compl p r a ha, mix_compl q r a ha] using hiff

theorem indiff_mix_of_indiff
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (hRat : P.RationalOn S)
    (hInd : VNMIndependent P S)
    (hS : MixtureClosed S)
    {p p' q q' : Lottery Outcome}
    (hp : p ∈ S) (hp' : p' ∈ S) (hq : q ∈ S) (hq' : q' ∈ S)
    (hpp' : P.Indiff p p') (hqq' : P.Indiff q q')
    (a : NNReal) (ha : a ≤ 1) :
    P.Indiff (mix p q a ha) (mix p' q' a ha) := by
  have hpqS : mix p q a ha ∈ S := hS hp hq a ha
  have hp'qS : mix p' q a ha ∈ S := hS hp' hq a ha
  have hp'q'S : mix p' q' a ha ∈ S := hS hp' hq' a ha
  have hpq_pref_hp'q :
      P.weakPref (mix p q a ha) (mix p' q a ha) :=
    weakPref_mix_left_of_independent hRat hInd hp hp' hq hpp'.1 a ha
  have hp'q_pref_hp'q' :
      P.weakPref (mix p' q a ha) (mix p' q' a ha) :=
    weakPref_mix_right_of_independent hRat hInd hq hq' hp' hqq'.1 a ha
  have hp'q'_pref_hp'q :
      P.weakPref (mix p' q' a ha) (mix p' q a ha) :=
    weakPref_mix_right_of_independent hRat hInd hq' hq hp' hqq'.2 a ha
  have hp'q_pref_hpq :
      P.weakPref (mix p' q a ha) (mix p q a ha) :=
    weakPref_mix_left_of_independent hRat hInd hp' hp hq hpp'.2 a ha
  constructor
  · exact hRat.2 hpqS hp'qS hp'q'S hpq_pref_hp'q hp'q_pref_hp'q'
  · exact hRat.2 hp'q'S hp'qS hpqS hp'q'_pref_hp'q hp'q_pref_hpq

/--
Archimedean/mixture continuity: if `p ≽ q ≽ r`, then `q` is indifferent to a
mixture of `p` and `r`.
-/
def VNMContinuous
    (P : Preference (Lottery Outcome))
    (S : Set (Lottery Outcome)) : Prop :=
  ∀ ⦃p q r : Lottery Outcome⦄,
    p ∈ S → q ∈ S → r ∈ S →
      P.weakPref p q → P.weakPref q r →
        ∃ (a : NNReal), ∃ (ha : a ≤ 1),
          P.Indiff (mix p r a ha) q

/-- The rationality plus mixture axioms used by the vNM utility theorem. -/
def VNMRational
    (P : Preference (Lottery Outcome))
    (S : Set (Lottery Outcome)) : Prop :=
  P.RationalOn S ∧ MixtureClosed S ∧ VNMIndependent P S ∧ VNMContinuous P S

/--
Expected-utility representation, abstracted as ordinary utility representation
on a carrier of lotteries.

Later finite-support specializations can identify `U` with the expectation of
an outcome utility index.  Keeping this definition separate avoids baking a
specific integrability or support assumption into the public API.
-/
def ExpectedUtilityRepresentsOn
    (P : Preference (Lottery Outcome))
    (S : Set (Lottery Outcome))
    (U : Lottery Outcome → ℝ) : Prop :=
  P.RepresentsOn S U

/--
Finite expected-utility representation by an outcome utility index.

This is the concrete representation form used in the vNM theorem.
-/
def ExpectedValueRepresentsOn [Fintype Outcome]
    (P : Preference (Lottery Outcome))
    (S : Set (Lottery Outcome))
    (u : Outcome → ℝ) : Prop :=
  ExpectedUtilityRepresentsOn P S (expectedValue u)

theorem expectedValue_generatedPref_representsOn [Fintype Outcome]
    (u : Outcome → ℝ) (S : Set (Lottery Outcome)) :
    ExpectedValueRepresentsOn
      (Utility.generatedPref (expectedValue u)) S u := by
  intro p q _hp _hq
  rfl

theorem expectedValue_generatedPref_independent [Fintype Outcome]
    (u : Outcome → ℝ) (S : Set (Lottery Outcome)) :
    VNMIndependent (Utility.generatedPref (expectedValue u)) S := by
  intro p q r _hp _hq _hr a ha hpos
  have haR : 0 < (a : ℝ) := by
    exact_mod_cast hpos
  simp [Utility.generatedPref, expectedValue_mix]
  constructor
  · intro h
    nlinarith
  · intro h
    nlinarith

theorem expectedValue_generatedPref_continuous [Fintype Outcome]
    (u : Outcome → ℝ) (S : Set (Lottery Outcome)) :
    VNMContinuous (Utility.generatedPref (expectedValue u)) S := by
  intro p q r _hp _hq _hr hpq hqr
  let Up := expectedValue u p
  let Uq := expectedValue u q
  let Ur := expectedValue u r
  change Up ≥ Uq at hpq
  change Uq ≥ Ur at hqr
  by_cases hEq : Up = Ur
  · refine ⟨1, le_rfl, ?_⟩
    have hUq : Uq = Up := by
      nlinarith
    constructor
    · change expectedValue u (mix p r 1 le_rfl) ≥ Uq
      rw [expectedValue_mix]
      simp [Up, Uq, hUq]
    · change Uq ≥ expectedValue u (mix p r 1 le_rfl)
      rw [expectedValue_mix]
      simp [Up, Uq, hUq]
  · have hUrUp : Ur < Up := by
      have hle : Ur ≤ Up := by
        linarith
      exact lt_of_le_of_ne hle (Ne.symm hEq)
    let aR : ℝ := (Uq - Ur) / (Up - Ur)
    have haR_nonneg : 0 ≤ aR := by
      dsimp [aR]
      exact div_nonneg (by linarith) (by linarith)
    have haR_le_one : aR ≤ 1 := by
      dsimp [aR]
      rw [div_le_one (by linarith)]
      linarith
    let a : NNReal := Real.toNNReal aR
    have ha : a ≤ 1 := by
      dsimp [a]
      rw [Real.toNNReal_le_one]
      exact haR_le_one
    refine ⟨a, ha, ?_⟩
    have ha_coe : (a : ℝ) = aR := by
      exact Real.coe_toNNReal aR haR_nonneg
    have hsub_coe : ((1 - a : NNReal) : ℝ) = 1 - aR := by
      rw [NNReal.coe_sub ha, ha_coe]
      norm_num
    have hmix : expectedValue u (mix p r a ha) = Uq := by
      rw [expectedValue_mix]
      rw [ha_coe, hsub_coe]
      change aR * Up + (1 - aR) * Ur = Uq
      dsimp [aR]
      have hden_ne : Up - Ur ≠ 0 := by
        nlinarith
      field_simp [hden_ne]
      ring
    constructor
    · change expectedValue u (mix p r a ha) ≥ Uq
      rw [hmix]
    · change Uq ≥ expectedValue u (mix p r a ha)
      rw [hmix]

theorem expectedValue_generatedPref_vnmRational [Fintype Outcome]
    (u : Outcome → ℝ) {S : Set (Lottery Outcome)}
    (hS : MixtureClosed S) :
    VNMRational (Utility.generatedPref (expectedValue u)) S := by
  exact
    ⟨(Utility.generatedPref (expectedValue u)).rationalOn_of_representsOn
        (expectedValue_generatedPref_representsOn u S),
      hS,
      expectedValue_generatedPref_independent u S,
      expectedValue_generatedPref_continuous u S⟩

theorem rationalOn_of_vnmRational
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (h : VNMRational P S) :
    P.RationalOn S :=
  h.1

theorem independent_of_vnmRational
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (h : VNMRational P S) :
    VNMIndependent P S :=
  h.2.2.1

theorem continuous_of_vnmRational
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (h : VNMRational P S) :
    VNMContinuous P S :=
  h.2.2.2

theorem mixtureClosed_of_vnmRational
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    (h : VNMRational P S) :
    MixtureClosed S :=
  h.2.1

theorem rationalOn_of_expectedUtilityRepresentsOn
    {P : Preference (Lottery Outcome)} {S : Set (Lottery Outcome)}
    {U : Lottery Outcome → ℝ}
    (hRep : ExpectedUtilityRepresentsOn P S U) :
    P.RationalOn S :=
  P.rationalOn_of_representsOn hRep

theorem vnmIndependent_of_expectedValueRepresentsOn [Fintype Outcome]
    {P : Preference (Lottery Outcome)}
    {S : Set (Lottery Outcome)}
    {u : Outcome → ℝ}
    (hS : MixtureClosed S)
    (hRep : ExpectedValueRepresentsOn P S u) :
    VNMIndependent P S := by
  intro p q r hp hq hr a ha hpos
  have haR : 0 < (a : ℝ) := by
    exact_mod_cast hpos
  have hpr : mix p r a ha ∈ S := hS hp hr a ha
  have hqr : mix q r a ha ∈ S := hS hq hr a ha
  rw [hRep hp hq, hRep hpr hqr]
  rw [expectedValue_mix, expectedValue_mix]
  constructor
  · intro h
    nlinarith
  · intro h
    nlinarith

theorem vnmContinuous_of_expectedValueRepresentsOn [Fintype Outcome]
    {P : Preference (Lottery Outcome)}
    {S : Set (Lottery Outcome)}
    {u : Outcome → ℝ}
    (hS : MixtureClosed S)
    (hRep : ExpectedValueRepresentsOn P S u) :
    VNMContinuous P S := by
  intro p q r hp hq hr hpq hqr
  let Up := expectedValue u p
  let Uq := expectedValue u q
  let Ur := expectedValue u r
  have hpqU : Up ≥ Uq := by
    change expectedValue u p ≥ expectedValue u q
    exact (hRep hp hq).mp hpq
  have hqrU : Uq ≥ Ur := by
    change expectedValue u q ≥ expectedValue u r
    exact (hRep hq hr).mp hqr
  by_cases hEq : Up = Ur
  · refine ⟨1, le_rfl, ?_⟩
    have hUq : Uq = Up := by
      nlinarith
    have hmixS : mix p r 1 le_rfl ∈ S := hS hp hr 1 le_rfl
    have hmix : expectedValue u (mix p r 1 le_rfl) = Uq := by
      rw [expectedValue_mix]
      simp [Up, Uq, hUq]
    constructor
    · exact (hRep hmixS hq).mpr (by rw [hmix])
    · exact (hRep hq hmixS).mpr (by rw [hmix])
  · have hUrUp : Ur < Up := by
      have hle : Ur ≤ Up := by
        linarith
      exact lt_of_le_of_ne hle (Ne.symm hEq)
    let aR : ℝ := (Uq - Ur) / (Up - Ur)
    have haR_nonneg : 0 ≤ aR := by
      dsimp [aR]
      exact div_nonneg (by linarith) (by linarith)
    have haR_le_one : aR ≤ 1 := by
      dsimp [aR]
      rw [div_le_one (by linarith)]
      linarith
    let a : NNReal := Real.toNNReal aR
    have ha : a ≤ 1 := by
      dsimp [a]
      rw [Real.toNNReal_le_one]
      exact haR_le_one
    refine ⟨a, ha, ?_⟩
    have hmixS : mix p r a ha ∈ S := hS hp hr a ha
    have ha_coe : (a : ℝ) = aR := by
      exact Real.coe_toNNReal aR haR_nonneg
    have hsub_coe : ((1 - a : NNReal) : ℝ) = 1 - aR := by
      rw [NNReal.coe_sub ha, ha_coe]
      norm_num
    have hmix : expectedValue u (mix p r a ha) = Uq := by
      rw [expectedValue_mix]
      rw [ha_coe, hsub_coe]
      change aR * Up + (1 - aR) * Ur = Uq
      dsimp [aR]
      have hden_ne : Up - Ur ≠ 0 := by
        nlinarith
      field_simp [hden_ne]
      ring
    constructor
    · exact (hRep hmixS hq).mpr (by rw [hmix])
    · exact (hRep hq hmixS).mpr (by rw [hmix])

theorem vnmRational_of_expectedValueRepresentsOn [Fintype Outcome]
    {P : Preference (Lottery Outcome)}
    {S : Set (Lottery Outcome)}
    {u : Outcome → ℝ}
    (hS : MixtureClosed S)
    (hRep : ExpectedValueRepresentsOn P S u) :
    VNMRational P S :=
  ⟨rationalOn_of_expectedUtilityRepresentsOn hRep,
    hS,
    vnmIndependent_of_expectedValueRepresentsOn hS hRep,
    vnmContinuous_of_expectedValueRepresentsOn hS hRep⟩

end ExpectedUtility
end GameTheory
end EcoLean
